import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, ExternalLink, Heart, Palette } from 'lucide-react';
import { Seo } from '@/components/Seo';

const sources=[
 {name:'PubMed / Psychonomic Bulletin & Review: systematic review of colour and emotion',url:'https://pubmed.ncbi.nlm.nih.gov/39806242/'},
 {name:'PubMed: living environment and depressive mood — systematic review',url:'https://pubmed.ncbi.nlm.nih.gov/29212385/'},
 {name:'PubMed: natural environments and depressive mood — systematic review and meta-analysis',url:'https://pubmed.ncbi.nlm.nih.gov/31362251/'},
];
export function ColorWellbeingArticlePage(){return <>
<Seo title="Värit, tunteet ja hyvinvointi – mitä tutkimus oikeasti kertoo?" description="Miten värit liittyvät iloon, rauhaan, energiaan ja tilakokemukseen? Tutkimukseen perustuva opas ilman väripsykologian ylilupauksia." path="/blogi/varit-tunteet-ja-hyvinvointi" />
<main className="bg-white"><section className="bg-navy-950 px-4 py-16 text-white sm:py-24"><div className="container-base max-w-4xl"><span className="inline-flex items-center gap-2 text-sm font-bold text-orange-300"><Heart className="h-4 w-4"/>Värit & hyvinvointi</span><h1 className="mt-5 font-display text-4xl font-extrabold leading-tight sm:text-6xl">Voiko väri tehdä elämästä onnellisempaa?</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-navy-200">Värit voivat muuttaa tilan tunnelmaa ja ihmiset yhdistävät värejä tunteisiin yllättävän johdonmukaisesti. Tutkimus ei kuitenkaan tue yksinkertaista lupausta, että tietty seinäväri parantaisi mielialan tai terveyden. Tässä erotamme kiinnostavan tutkimuksen väripsykologian myyteistä.</p></div></section>
<section className="container-base max-w-4xl px-4 py-12 sm:px-0 sm:py-16"><div className="prose prose-lg max-w-none text-navy-700"><h2 className="font-display text-3xl font-extrabold text-navy-950">Mitä tutkimus kertoo?</h2><p className="mt-4 leading-8">Vuonna 2025 julkaistu systemaattinen katsaus kokosi 132 vertaisarvioitua tutkimusta, yhteensä 42 266 osallistujaa 64 maasta. Katsauksessa löytyi systemaattisia väri–tunne-yhteyksiä: esimerkiksi keltainen ja oranssi yhdistyivät usein positiivisiin, aktiivisiin tunteisiin, kun taas sininen, vihreä ja valkoinen yhdistyivät useammin positiivisiin ja rauhallisempiin tunteisiin.</p><div className="my-8 rounded-3xl bg-orange-50 p-6"><strong className="text-navy-950">Tärkeä raja:</strong> suurin osa tästä näytöstä koskee sitä, mitä tunteita ihmiset <em>yhdistävät</em> väreihin. Se ei todista, että huoneen maalaaminen tietyllä värillä aiheuttaisi saman tunteen jokaiselle.</div><h2 className="font-display text-3xl font-extrabold text-navy-950">Hyvä tila on enemmän kuin seinän väri</h2><p className="mt-4 leading-8">Asuin- ja rakennettu ympäristö kokonaisuutena liittyy hyvinvointiin. Tutkimuksissa esimerkiksi asumisen laatu, toimivuus, melu, ilmanlaatu ja viherympäristö ovat olleet yhteydessä mielialaan. Siksi värisuunnittelua kannattaa ajatella yhtenä osana viihtyisää, toimivaa ja henkilökohtaista tilaa — ei hoitona.</p><h2 className="font-display text-3xl font-extrabold text-navy-950">Koti, koulu, päiväkoti, toimisto ja liiketila tarvitsevat eri ratkaisuja</h2><p className="mt-4 leading-8">Kodin värissä oma mieltymys voi olla tärkein. Päiväkodissa tai koulussa kannattaa huomioida myös tilan tehtävä, valaistus, kontrastit ja rauhallisten sekä aktiivisten alueiden ero. Toimistossa selkeys ja pitkäaikainen viihtyvyys voivat olla tärkeämpiä kuin trendiväri. Liikkeessä väri voi puolestaan tukea paikan identiteettiä ja asiakkaan kokemusta.</p><h2 className="font-display text-3xl font-extrabold text-navy-950">Kokeile ennen kuin maalaat</h2><p className="mt-4 leading-8">Paras väri ei synny taulukosta. Aloita siitä, millaisen tunnelman haluat, katso sävyä oman tilan valossa ja vertaa vaihtoehtoja. VäriLab auttaa löytämään lähtöpaletin ja VäriKamussa voit kokeilla ajatusta omaan kuvaasi ennen päätöstä.</p></div><div className="mt-10 flex flex-wrap gap-3"><Link to="/varilab" className="btn-primary"><Palette className="h-4 w-4"/>Tee VäriLab-värivisa <ArrowRight className="h-4 w-4"/></Link><Link to="/app/varikamu" className="btn-outline">Kokeile VäriKamussa</Link></div>
<div className="mt-14 border-t border-navy-100 pt-8"><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-orange-600"/><h2 className="font-display text-2xl font-extrabold text-navy-950">Tutkimuslähteet</h2></div><p className="mt-2 text-sm leading-6 text-navy-600">Linkit vievät alkuperäisten tutkimusten PubMed-tietueisiin. Näin voit tarkistaa lähteet itse.</p><div className="mt-5 space-y-3">{sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer" className="flex items-start justify-between gap-4 rounded-2xl border border-navy-100 p-4 font-semibold text-navy-800 transition hover:border-orange-300 hover:bg-orange-50"><span>{s.name}</span><ExternalLink className="mt-1 h-4 w-4 shrink-0 text-orange-600"/></a>)}</div></div></section></main></>}
