import { useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Brush, Camera, Download, Droplets, Eraser, Hand, Sparkles, SprayCan, Undo2, Upload, type LucideIcon } from 'lucide-react';
import { MaskLayer } from '@/lib/engine/MaskLayer';
import { SegmentationProvider } from '@/lib/ai/SegmentationProvider';

type Point={x:number;y:number};
type Tool='sponge'|'brush'|'spray'|'squeegee'|'eraser';
type ToolDef={label:string;size:number;power:number;icon:LucideIcon;hint:string};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const segmentation=new SegmentationProvider();
const defs:Record<Tool,ToolDef>={
 sponge:{label:'Sieni / käsin',size:68,power:.72,icon:Hand,hint:'Yleispuhdistus ja pöly'},
 brush:{label:'Pehmeä harja',size:44,power:.9,icon:Brush,hint:'Pinttynyt lika ja saumat'},
 spray:{label:'Puhdistussuihke',size:96,power:.58,icon:SprayCan,hint:'Laaja kevyt esikäsittely'},
 squeegee:{label:'Ikkunalasta',size:78,power:.94,icon:Droplets,hint:'Lasi, peilit ja sileät pinnat'},
 eraser:{label:'Poista puhdistus',size:52,power:1,icon:Eraser,hint:'Palauta alkuperäinen kohta'}
};

export function SiivouskamuEnterpriseStudioPage(){
 const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imgRef=useRef<HTMLImageElement>(null),stageRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),sourceRef=useRef<HTMLCanvasElement|null>(null),maskRef=useRef<MaskLayer|null>(null);
 const drawing=useRef(false),last=useRef<Point|null>(null),stroke=useRef<Point[]>([]);
 const [url,setUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('sponge'),[toolSize,setToolSize]=useState(68),[intensity,setIntensity]=useState(82),[smart,setSmart]=useState(true),[busy,setBusy]=useState(false),[before,setBefore]=useState(false),[history,setHistory]=useState<number[][]>([]),[message,setMessage]=useState('Pyyhi likaista kohtaa. Muutos näkyy heti, mutta pinta, reunat ja yksityiskohdat säilyvät.');
 const load=(f?:File)=>{if(!f||!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>12*1024*1024)return;if(url?.startsWith('blob:'))URL.revokeObjectURL(url);setUrl(URL.createObjectURL(f));setHistory([]);setBefore(false)};
 const loaded=()=>{const img=imgRef.current,out=canvasRef.current;if(!img||!out)return;const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));setSize({width:w,height:h});out.width=w;out.height=h;const source=document.createElement('canvas');source.width=w;source.height=h;source.getContext('2d')!.drawImage(img,0,0,w,h);sourceRef.current=source;maskRef.current=new MaskLayer(w,h);render();setHistory([maskRef.current.toRle()])};
 const render=()=>{const out=canvasRef.current,source=sourceRef.current,mask=maskRef.current;if(!out||!source||!mask)return;const sctx=source.getContext('2d'),octx=out.getContext('2d');if(!sctx||!octx)return;const src=sctx.getImageData(0,0,source.width,source.height),dst=octx.createImageData(source.width,source.height);dst.data.set(src.data);const global=intensity/100;for(let i=0;i<mask.alpha.length;i++){const ma=mask.alpha[i]/255;if(ma<=0)continue;const p=i*4,r=src.data[p],g=src.data[p+1],b=src.data[p+2];const lum=.299*r+.587*g+.114*b;const shadow=Math.max(0,(150-lum)/150);const chroma=(Math.max(r,g,b)-Math.min(r,g,b))/255;const strength=clamp(ma*global,0,1);const grimeLift=(10+20*shadow+10*chroma)*strength;const targetLum=clamp(lum+grimeLift,0,255);const neutral=.18*strength;let nr=r+(targetLum-lum)+(lum-r)*neutral;let ng=g+(targetLum-lum)+(lum-g)*neutral;let nb=b+(targetLum-lum)+(lum-b)*neutral;const detail=(lum-128)*.035*strength;nr+=detail;ng+=detail;nb+=detail;dst.data[p]=clamp(Math.round(nr),0,255);dst.data[p+1]=clamp(Math.round(ng),0,255);dst.data[p+2]=clamp(Math.round(nb),0,255);dst.data[p+3]=255}octx.putImageData(dst,0,0)};
 const point=(e:ReactPointerEvent<HTMLDivElement>)=>{const el=stageRef.current;if(!el||!size.width)return null;const r=el.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*size.width,0,size.width-1),y:clamp((e.clientY-r.top)/r.height*size.height,0,size.height-1)}};
 const line=(a:Point,b:Point,width:number)=>{const c=document.createElement('canvas');c.width=size.width;c.height=size.height;const x=c.getContext('2d')!,d=defs[tool];x.strokeStyle='#fff';x.lineWidth=width;x.lineCap=tool==='squeegee'?'square':'round';x.lineJoin='round';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();const data=x.getImageData(0,0,c.width,c.height).data,m=new MaskLayer(c.width,c.height);for(let i=0;i<m.alpha.length;i++){const alpha=data[i*4+3]/255;m.alpha[i]=Math.round(alpha*d.power*255)}return m};
 const apply=(a:Point,b:Point)=>{const m=maskRef.current;if(!m)return;const strokeMask=line(a,b,tool==='spray'?toolSize*1.4:toolSize);maskRef.current=tool==='eraser'?m.subtract(strokeMask):m.union(strokeMask);render()};
 const smartComplete=async(seed:Point)=>{const source=sourceRef.current,current=maskRef.current;if(!source||!current)return;setBusy(true);try{const data=source.getContext('2d')!.getImageData(0,0,source.width,source.height);const result=await segmentation.segment({imageId:`clean:${url}`,image:data,point:seed,tolerance:26});const coverage=result.mask.coverage();if(coverage>.30||coverage<.001){setMessage('Smart ei laajentanut aluetta, koska tunnistus ei ollut turvallinen. Oma pyyhintä säilyi.');return}const smartMask=result.mask.clone();for(let i=0;i<smartMask.alpha.length;i++)smartMask.alpha[i]=Math.round(smartMask.alpha[i]*.72);maskRef.current=current.union(smartMask);render();setMessage(result.source==='remote-sam'?'Smart tunnisti puhdistettavan pinnan.':'Smart täydensi vain turvallisen samankaltaisen alueen.')}catch{setMessage('Smart ei ollut käytettävissä. Manuaalinen puhdistus toimii silti normaalisti.')}finally{setBusy(false)}};
 const down=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!url||before)return;e.preventDefault();const p=point(e);if(!p)return;e.currentTarget.setPointerCapture?.(e.pointerId);drawing.current=true;last.current=p;stroke.current=[p]};
 const move=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawing.current||!last.current)return;e.preventDefault();const p=point(e);if(!p)return;apply(last.current,p);last.current=p;stroke.current.push(p)};
 const up=()=>{if(!drawing.current)return;drawing.current=false;const pts=stroke.current;last.current=null;stroke.current=[];if(maskRef.current)setHistory(h=>[...h.slice(-19),maskRef.current!.toRle()]);if(smart&&tool!=='eraser'&&pts.length>1)void smartComplete(pts[Math.floor(pts.length/2)]);setMessage(tool==='eraser'?'Puhdistus poistettiin valitulta kohdalta.':'Puhdistus näkyy heti kuvassa. Käytä Ennen/Jälkeen tarkistukseen.')};
 const undo=()=>{if(history.length<2||!size.width)return;const next=history.slice(0,-1),r=next[next.length-1];maskRef.current=MaskLayer.fromRle(size.width,size.height,r);setHistory(next);render()};
 const reset=()=>{maskRef.current?.clear();render();if(maskRef.current)setHistory([maskRef.current.toRle()])};
 const download=()=>{const c=canvasRef.current;if(!c)return;const a=document.createElement('a');a.download=`siivouskamu-${Date.now()}.jpg`;a.href=c.toDataURL('image/jpeg',.94);a.click()};
 return <section className="min-h-screen bg-navy-50 px-2 py-3 pb-28 lg:pb-6"><div className="container-base max-w-6xl"><div className="mb-3"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">SiivousKamu Enterprise</p><h1 className="font-display text-xl font-extrabold text-navy-950 sm:text-2xl">Pyyhi lika pois – näe luonnollinen puhdistettu pinta</h1><p className="mt-1 text-sm text-navy-600">Ei värillistä peittoa eikä valkoista maalia. Muutos tehdään alkuperäisen kuvan pikseleihin vain puhdistusalueella.</p></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="card p-2 sm:p-3">{!url?<div className="grid min-h-[48vh] place-items-center rounded-2xl border-2 border-dashed border-navy-200"><div className="text-center"><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-3 text-xl font-bold">Ota tai lataa likaisen pinnan kuva</h2><div className="mt-4 flex justify-center gap-2"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/>Ota kuva</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Lataa</button></div></div></div>:<><div className="flex min-h-[300px] items-center justify-center overflow-hidden rounded-2xl bg-navy-950"><div ref={stageRef} className="relative w-full max-w-full overflow-hidden" style={{aspectRatio:`${size.width}/${size.height}`,touchAction:'none'}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><img ref={imgRef} src={url} onLoad={loaded} draggable={false} className="pointer-events-none absolute inset-0 h-full w-full object-fill"/><canvas ref={canvasRef} className={`pointer-events-none absolute inset-0 h-full w-full ${before?'hidden':''}`}/></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button className={!before?'btn-primary':'btn-outline'} onClick={()=>setBefore(false)}>Jälkeen</button><button className={before?'btn-primary':'btn-outline'} onClick={()=>setBefore(true)}>Ennen</button></div><div className="mt-3 hidden flex-wrap gap-2 lg:flex"><button className="btn-outline" onClick={undo}><Undo2 className="size-4"/>Kumoa</button><button className="btn-outline" onClick={reset}>Tyhjennä</button><button className="btn-primary" onClick={download}><Download className="size-4"/>Lataa JPG</button></div></>}
<input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>load(e.target.files?.[0])}/><input ref={cameraRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>load(e.target.files?.[0])}/></div><aside className="space-y-3"><div className="card p-4"><h2 className="font-bold">Puhdistusväline</h2><div className="mt-3 grid grid-cols-2 gap-2">{(Object.keys(defs) as Tool[]).map(id=>{const d=defs[id],Icon=d.icon;return <button key={id} className={tool===id?'btn-primary':'btn-outline'} onClick={()=>{setTool(id);setToolSize(d.size)}}><Icon className="size-4"/>{d.label}</button>})}</div><p className="mt-2 text-xs text-navy-500">{defs[tool].hint}</p><button className={`mt-3 w-full rounded-xl border p-3 text-left ${smart?'border-orange-400 bg-orange-50':'border-navy-200'}`} onClick={()=>setSmart(v=>!v)}><strong><Sparkles className="mr-1 inline size-4"/>Smart {smart?'ON':'OFF'} {busy?'· tunnistaa…':''}</strong><span className="block text-xs text-navy-600">Oma pyyhintä säilyy aina. Smart laajentaa vain turvallisen alueen.</span></button></div><div className="card p-4"><h2 className="font-bold">Koko ja puhdistusteho</h2><label className="mt-3 block text-sm font-bold">Työkalun koko {toolSize}px<input className="mt-2 w-full accent-orange-500" type="range" min="16" max="150" value={toolSize} onChange={e=>setToolSize(Number(e.target.value))}/></label><label className="mt-4 block text-sm font-bold">Puhdistusteho {intensity}%<input className="mt-2 w-full accent-orange-500" type="range" min="10" max="100" value={intensity} onChange={e=>{setIntensity(Number(e.target.value));window.setTimeout(render,0)}}/></label></div><div className="card p-4"><p className="text-sm leading-6 text-navy-700">{message}</p><p className="mt-3 text-xs text-navy-500">Esikatselu simuloi puhdistusta valokuvassa. Se ei lupaa fyysisen puhdistuksen lopputulosta.</p></div></aside></div></div>{url&&<div className="fixed inset-x-0 bottom-0 z-50 border-t border-navy-100 bg-white/95 px-3 pb-[max(.6rem,env(safe-area-inset-bottom))] pt-2 shadow-[0_-12px_30px_rgba(15,23,42,.14)] backdrop-blur-xl lg:hidden"><div className="mx-auto flex max-w-xl gap-2"><button className="btn-outline flex-1" onClick={undo}><Undo2 className="size-4"/>Kumoa</button><button className="btn-outline flex-1" onClick={reset}>Tyhjennä</button><button className="btn-primary flex-[1.25]" onClick={download}><Download className="size-4"/>Tallenna</button></div></div>}</section>
}