import { useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Brush, Camera, Download, Droplets, Eraser, Hand, Sparkles, SprayCan, Undo2, Upload } from 'lucide-react';
import { CanvasPipeline } from '@/lib/engine/CanvasPipeline';
import { MaskLayer } from '@/lib/engine/MaskLayer';
import { SegmentationProvider } from '@/lib/ai/SegmentationProvider';

type Point={x:number;y:number};
type Tool='sponge'|'brush'|'spray'|'squeegee'|'eraser';
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const segmentation=new SegmentationProvider();
const defs={sponge:{label:'Sieni / käsin',size:64,intensity:.72,icon:Hand},brush:{label:'Pehmeä harja',size:42,intensity:.86,icon:Brush},spray:{label:'Puhdistussuihke',size:92,intensity:.55,icon:SprayCan},squeegee:{label:'Ikkunalasta',size:76,intensity:.9,icon:Droplets},eraser:{label:'Poista puhdistus',size:48,intensity:0,icon:Eraser}} as const;

export function SiivouskamuEnterpriseStudioPage(){
 const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imgRef=useRef<HTMLImageElement>(null),stageRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),sourceRef=useRef<HTMLCanvasElement|null>(null),maskRef=useRef<MaskLayer|null>(null);
 const drawing=useRef(false),last=useRef<Point|null>(null),stroke=useRef<Point[]>([]);
 const [url,setUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('sponge'),[toolSize,setToolSize]=useState(64),[intensity,setIntensity]=useState(75),[smart,setSmart]=useState(true),[busy,setBusy]=useState(false),[before,setBefore]=useState(false),[history,setHistory]=useState<number[][]>([]),[message,setMessage]=useState('Pyyhi likaista kohtaa. SiivousKamu säilyttää alkuperäisen pinnan ja muuttaa vain puhdistusmaskia.');
 const load=(f?:File)=>{if(!f||!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>12*1024*1024)return;if(url?.startsWith('blob:'))URL.revokeObjectURL(url);setUrl(URL.createObjectURL(f));setHistory([]);setBefore(false);};
 const loaded=()=>{const img=imgRef.current,out=canvasRef.current;if(!img||!out)return;const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.round(img.naturalWidth*scale),h=Math.round(img.naturalHeight*scale);setSize({width:w,height:h});out.width=w;out.height=h;const source=document.createElement('canvas');source.width=w;source.height=h;source.getContext('2d')!.drawImage(img,0,0,w,h);sourceRef.current=source;maskRef.current=new MaskLayer(w,h);render();setHistory([maskRef.current.toRle()]);};
 const render=()=>{const out=canvasRef.current,source=sourceRef.current,mask=maskRef.current;if(!out||!source||!mask)return;const p=new CanvasPipeline(out);p.setSize({width:source.width,height:source.height});p.renderBaseImage(source);p.applyCleaningMask(mask,{intensity:intensity/100,quality:'final'});};
 const point=(e:ReactPointerEvent<HTMLDivElement>)=>{const el=stageRef.current;if(!el||!size.width)return null;const r=el.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*size.width,0,size.width-1),y:clamp((e.clientY-r.top)/r.height*size.height,0,size.height-1)};};
 const line=(a:Point,b:Point,width:number)=>{const c=document.createElement('canvas');c.width=size.width;c.height=size.height;const x=c.getContext('2d')!;x.strokeStyle='#fff';x.lineWidth=width;x.lineCap=tool==='squeegee'?'square':'round';x.lineJoin='round';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();const d=x.getImageData(0,0,c.width,c.height).data,m=new MaskLayer(c.width,c.height);for(let i=0;i<m.alpha.length;i++)m.alpha[i]=d[i*4+3];return m;};
 const apply=(a:Point,b:Point)=>{const m=maskRef.current;if(!m)return;const strokeMask=line(a,b,tool==='spray'?toolSize*1.35:toolSize);maskRef.current=tool==='eraser'?m.subtract(strokeMask):m.union(strokeMask);render();};
 const smartComplete=async(seed:Point)=>{const source=sourceRef.current,current=maskRef.current;if(!source||!current)return;setBusy(true);try{const data=source.getContext('2d')!.getImageData(0,0,source.width,source.height);const result=await segmentation.segment({imageId:`clean:${url}`,image:data,point:seed,tolerance:28});const count=result.mask.alpha.reduce((n,a)=>n+(a?1:0),0),coverage=count/(source.width*source.height);if(coverage>.42||coverage<.001){setMessage('Smart ei levittänyt puhdistusta, koska pintavalinta ei ollut turvallinen. Oma pyyhintä säilyi.');return;}maskRef.current=current.union(result.mask);render();setMessage(result.source==='remote-sam'?'Smart tunnisti puhdistettavan pinnan. Pinta puhdistettiin ilman värillistä peittoa.':'Paikallinen Smart täydensi saman pinnan. Jos rajaus ei ole oikea, käytä Poista puhdistus -työkalua.');}catch{setMessage('Smart ei ollut käytettävissä. Manuaalinen puhdistus toimii edelleen.');}finally{setBusy(false);}};
 const down=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!url||before)return;e.preventDefault();const p=point(e);if(!p)return;e.currentTarget.setPointerCapture?.(e.pointerId);drawing.current=true;last.current=p;stroke.current=[p];};
 const move=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawing.current||!last.current)return;e.preventDefault();const p=point(e);if(!p)return;apply(last.current,p);last.current=p;stroke.current.push(p);};
 const up=()=>{if(!drawing.current)return;drawing.current=false;const pts=stroke.current;last.current=null;stroke.current=[];if(maskRef.current)setHistory(h=>[...h.slice(-19),maskRef.current!.toRle()]);if(smart&&tool!=='eraser'&&pts.length)void smartComplete(pts[Math.floor(pts.length/2)]);};
 const undo=()=>{if(history.length<2||!size.width)return;const next=history.slice(0,-1),r=next[next.length-1];maskRef.current=MaskLayer.fromRle(size.width,size.height,r);setHistory(next);render();};
 const reset=()=>{maskRef.current?.clear();render();if(maskRef.current)setHistory([maskRef.current.toRle()]);};
 const download=()=>{const c=canvasRef.current;if(!c)return;const a=document.createElement('a');a.download=`siivouskamu-${Date.now()}.jpg`;a.href=c.toDataURL('image/jpeg',.94);a.click();};
 return <section className="min-h-screen bg-navy-50 px-2 py-4"><div className="container-base max-w-6xl"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">SiivousKamu Enterprise</p><h1 className="font-display text-2xl font-extrabold text-navy-950">Pyyhi lika pois – näe luonnollinen puhdistettu pinta</h1><p className="mt-1 text-sm text-navy-600">Ei turkoosia peittoa eikä valkoista maalia. Puhdistus säilyttää kuvan pinnat, reunat ja yksityiskohdat.</p></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="card p-3">{!url?<div className="grid min-h-[50vh] place-items-center rounded-2xl border-2 border-dashed border-navy-200"><div className="text-center"><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-3 text-xl font-bold">Ota tai lataa likaisen pinnan kuva</h2><div className="mt-4 flex gap-2"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/>Ota kuva</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Lataa</button></div></div></div>:<><div className="flex min-h-[300px] items-center justify-center overflow-hidden rounded-2xl bg-navy-950"><div ref={stageRef} className="relative w-full max-w-full overflow-hidden" style={{aspectRatio:`${size.width}/${size.height}`,touchAction:'none'}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><img ref={imgRef} src={url} onLoad={loaded} draggable={false} className="pointer-events-none absolute inset-0 h-full w-full object-fill"/><canvas ref={canvasRef} className={`pointer-events-none absolute inset-0 h-full w-full ${before?'hidden':''}`}/></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button className={!before?'btn-primary':'btn-outline'} onClick={()=>setBefore(false)}>Jälkeen</button><button className={before?'btn-primary':'btn-outline'} onClick={()=>setBefore(true)}>Ennen</button></div><div className="mt-3 flex flex-wrap gap-2"><button className="btn-outline" onClick={undo}><Undo2 className="size-4"/>Kumoa</button><button className="btn-outline" onClick={reset}>Tyhjennä</button><button className="btn-primary" onClick={download}><Download className="size-4"/>Lataa JPG</button></div></>}
<input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>load(e.target.files?.[0])}/><input ref={cameraRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>load(e.target.files?.[0])}/></div><aside className="space-y-4"><div className="card p-4"><h2 className="font-bold">1. Puhdistusväline</h2><div className="mt-3 grid grid-cols-2 gap-2">{(Object.keys(defs) as Tool[]).map(id=>{const d=defs[id],Icon=d.icon;return <button key={id} className={tool===id?'btn-primary':'btn-outline'} onClick={()=>{setTool(id);setToolSize(d.size);}}><Icon className="size-4"/>{d.label}</button>})}</div><button className={`mt-3 w-full rounded-xl border p-3 text-left ${smart?'border-orange-400 bg-orange-50':'border-navy-200'}`} onClick={()=>setSmart(v=>!v)}><strong><Sparkles className="mr-1 inline size-4"/>Smart {smart?'ON':'OFF'} {busy?'· tunnistaa…':''}</strong><span className="block text-xs text-navy-600">Pyyhintäsi säilyy aina. Smart täydentää vain turvallisen pinnan.</span></button></div><div className="card p-4"><h2 className="font-bold">2. Koko ja puhdistusteho</h2><label className="mt-3 block text-sm font-bold">Työkalun koko {toolSize}px<input className="mt-2 w-full accent-orange-500" type="range" min="16" max="140" value={toolSize} onChange={e=>setToolSize(Number(e.target.value))}/></label><label className="mt-4 block text-sm font-bold">Puhdistusteho {intensity}%<input className="mt-2 w-full accent-orange-500" type="range" min="20" max="100" value={intensity} onChange={e=>{setIntensity(Number(e.target.value));window.setTimeout(render,0);}}/></label></div><div className="card p-4"><p className="text-sm leading-6 text-navy-700">{message}</p><p className="mt-3 text-xs text-navy-500">Esikatselu simuloi puhdistusta valokuvassa. Lopputulos riippuu oikeasta pinnasta, liasta ja puhdistusmenetelmästä.</p></div></aside></div></div></section>;
}