import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Camera, Download, Eye, EyeOff, Minus, Plus, Redo2, RotateCcw, Undo2, Upload } from 'lucide-react';
import { createSurfaceMask, editMaskCircle, maskCoverage, mergeMask } from '@/features/smart-segmentation/masks';
import { PromptFallbackProvider } from '@/features/smart-segmentation/provider';
import { renderSurfaceMasks } from '@/features/smart-segmentation/render';
import { cloneMasks } from '@/features/smart-segmentation/history';
import type { MaskEditMode, SegmentationPoint, SurfaceMask } from '@/features/smart-segmentation/types';
import { detectSmartSegmentationCapability } from '@/features/smart-segmentation/webgpu';

type ViewMode = 'after' | 'before' | 'compare';
type HistoryState = { masks: SurfaceMask[]; activeId: string | null };
const palette = ['#F2EFE6','#D8C9B5','#C9CBC8','#A7B19B','#9FB4C3','#B86F52','#496255','#45494B','#1D2022','#D99518','#6C5CE7','#00B894'];
const fallback = new PromptFallbackProvider();

export function UniversalPaintStudioV3Page() {
  const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLImageElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),stageRef=useRef<HTMLDivElement>(null);
  const sourceRef=useRef<ImageData|null>(null),drawingRef=useRef(false),pointsRef=useRef<SegmentationPoint[]>([]);
  const [imageUrl,setImageUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0});
  const [masks,setMasks]=useState<SurfaceMask[]>([]),[activeId,setActiveId]=useState<string|null>(null),[mode,setMode]=useState<MaskEditMode>('add');
  const [color,setColor]=useState('#D99518'),[brushSize,setBrushSize]=useState(34),[viewMode,setViewMode]=useState<ViewMode>('after'),[compareAt,setCompareAt]=useState(50);
  const [history,setHistory]=useState<HistoryState[]>([]),[historyIndex,setHistoryIndex]=useState(-1),[status,setStatus]=useState('Lataa kuva ja valitse maalattava pinta.');
  const [semanticStatus,setSemanticStatus]=useState('Tarkistetaan laitetta…');

  const active=masks.find(m=>m.id===activeId)??null;
  useEffect(()=>{detectSmartSegmentationCapability().then(c=>setSemanticStatus(c.webGpu?'WebGPU valmis · semanttinen malli seuraavassa vaiheessa':'Paikallinen varatila käytössä'));},[]);
  useEffect(()=>{render();},[masks,viewMode,compareAt]);

  const commit=(next:SurfaceMask[],nextActive=activeId)=>{const snapshot={masks:cloneMasks(next),activeId:nextActive};const h=[...history.slice(0,historyIndex+1),snapshot].slice(-30);setMasks(next);setActiveId(nextActive);setHistory(h);setHistoryIndex(h.length-1);};
  const restore=(i:number)=>{const s=history[i];if(!s)return;setMasks(cloneMasks(s.masks));setActiveId(s.activeId);setHistoryIndex(i);};
  const undo=()=>historyIndex>0&&restore(historyIndex-1),redo=()=>historyIndex<history.length-1&&restore(historyIndex+1);

  const loadFile=(file?:File)=>{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024)return;if(imageUrl?.startsWith('blob:'))URL.revokeObjectURL(imageUrl);setImageUrl(URL.createObjectURL(file));setMasks([]);setActiveId(null);setHistory([]);setHistoryIndex(-1);setStatus('Kuva valmis. Lisää ensimmäinen pinta ja maalaa karkea vihje pinnan keskelle.');};
  const onImageLoad=()=>{const img=imageRef.current,canvas=canvasRef.current;if(!img||!canvas)return;const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight));const width=Math.max(1,Math.round(img.naturalWidth*scale)),height=Math.max(1,Math.round(img.naturalHeight*scale));setSize({width,height});canvas.width=width;canvas.height=height;const src=document.createElement('canvas');src.width=width;src.height=height;const ctx=src.getContext('2d');ctx?.drawImage(img,0,0,width,height);sourceRef.current=ctx?.getImageData(0,0,width,height)??null;const first=createSurfaceMask(width,height,color,'Pinta 1');setMasks([first]);setActiveId(first.id);setHistory([{masks:cloneMasks([first]),activeId:first.id}]);setHistoryIndex(0);requestAnimationFrame(render);};

  const render=()=>{const canvas=canvasRef.current,source=sourceRef.current;if(!canvas||!source)return;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,canvas.width,canvas.height);if(viewMode==='before')return;const rendered=renderSurfaceMasks(source,masks);if(viewMode==='after'){ctx.putImageData(rendered,0,0);return;}const temp=document.createElement('canvas');temp.width=source.width;temp.height=source.height;temp.getContext('2d')?.putImageData(rendered,0,0);ctx.save();ctx.beginPath();ctx.rect(0,0,source.width*(compareAt/100),source.height);ctx.clip();ctx.drawImage(temp,0,0);ctx.restore();};
  const point=(event:ReactPointerEvent<HTMLDivElement>)=>{const stage=stageRef.current;if(!stage||!size.width)return null;const r=stage.getBoundingClientRect();return{x:Math.max(0,Math.min(size.width-1,(event.clientX-r.left)/r.width*size.width)),y:Math.max(0,Math.min(size.height-1,(event.clientY-r.top)/r.height*size.height))};};
  const editAt=(x:number,y:number)=>{if(!active)return;const next=masks.map(m=>m.id===active.id?editMaskCircle(m,x,y,brushSize,mode):m);setMasks(next);};
  const pointerDown=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!active||viewMode==='before')return;const p=point(e);if(!p)return;e.currentTarget.setPointerCapture(e.pointerId);drawingRef.current=true;pointsRef.current=[{...p,label:mode==='add'?1:0}];editAt(p.x,p.y);};
  const pointerMove=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawingRef.current)return;const p=point(e);if(!p)return;pointsRef.current.push({...p,label:mode==='add'?1:0});editAt(p.x,p.y);};
  const pointerUp=()=>{if(!drawingRef.current)return;drawingRef.current=false;commit(masks);pointsRef.current=[];};

  const smartFill=async()=>{const source=sourceRef.current;if(!active||!source)return;const positive=pointsRef.current.filter(p=>p.label===1);const points=positive.length?positive:[{x:size.width/2,y:size.height/2,label:1 as const}];setStatus('Täytetään pintaa paikallisella varatilalla…');const result=await fallback.segment({image:source,points,width:size.width,height:size.height});const next=masks.map(m=>m.id===active.id?mergeMask(m,result.mask,'add'):m);commit(next);setStatus('Varatäyttö lisättiin. Korjaa rajaa + Lisää alue / − Poista alue -työkaluilla. Semanttinen malli liitetään tähän samaan maskiin.');};
  const addSurface=()=>{if(!size.width)return;const m=createSurfaceMask(size.width,size.height,color,`Pinta ${masks.length+1}`);commit([...masks,m],m.id);setStatus('Uusi pinta lisätty. Jokaisella pinnalla voi olla oma väri.');};
  const removeSurface=()=>{if(!active)return;const next=masks.filter(m=>m.id!==active.id);commit(next,next[0]?.id??null);};
  const setActiveColor=(nextColor:string)=>{setColor(nextColor);if(!active)return;commit(masks.map(m=>m.id===active.id?{...m,color:nextColor}:m));};
  const toggleVisible=(id:string)=>commit(masks.map(m=>m.id===id?{...m,visible:!m.visible}:m));
  const reset=()=>{if(!size.width)return;const m=createSurfaceMask(size.width,size.height,color,'Pinta 1');commit([m],m.id);};
  const download=(type:'png'|'jpg')=>{const img=imageRef.current,source=sourceRef.current;if(!img||!source)return;const out=document.createElement('canvas');out.width=source.width;out.height=source.height;const ctx=out.getContext('2d');if(!ctx)return;ctx.drawImage(img,0,0,out.width,out.height);const overlay=document.createElement('canvas');overlay.width=out.width;overlay.height=out.height;overlay.getContext('2d')?.putImageData(renderSurfaceMasks(source,masks),0,0);ctx.drawImage(overlay,0,0);ctx.fillStyle='rgba(255,255,255,.84)';ctx.fillRect(12,out.height-36,Math.min(350,out.width-24),24);ctx.fillStyle='#172033';ctx.font='12px sans-serif';ctx.fillText('VäriKamu · maalausmultivari.fi',20,out.height-20);const a=document.createElement('a');a.download=`varikamu-${Date.now()}.${type}`;a.href=type==='jpg'?out.toDataURL('image/jpeg',.92):out.toDataURL('image/png');a.click();};

  return <section className="min-h-screen bg-navy-50 px-2 py-3 sm:px-4"><div className="mx-auto max-w-7xl">
    <div className="mb-3"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">VäriKamu V3</p><h1 className="font-display text-xl font-extrabold text-navy-950 sm:text-2xl">Valitse pinta, korjaa rajat ja kokeile värejä</h1><p className="mt-1 text-sm text-navy-600">📷 Kuva → 🖌️ valitse pinta → ✨ täytä → ➕/➖ korjaa → 🎨 väri → 📨 suunnitelma</p></div>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_340px]">
      <div className="card min-w-0 p-2 sm:p-4">{!imageUrl?<div className="grid min-h-[55vh] place-items-center rounded-2xl border-2 border-dashed border-navy-200 bg-white p-6 text-center"><div><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-3 text-lg font-bold">Ota kuva tai lataa kuva</h2><div className="mt-4 flex flex-wrap justify-center gap-2"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/> Ota kuva</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/> Lataa kuva</button></div></div></div>:<><div ref={stageRef} className="relative mx-auto max-h-[64dvh] touch-none overflow-hidden rounded-xl bg-navy-950" style={{aspectRatio:size.width&&size.height?`${size.width}/${size.height}`:'4/3'}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><img ref={imageRef} src={imageUrl} onLoad={onImageLoad} className="absolute inset-0 h-full w-full object-contain" alt="Asiakkaan kuva"/><canvas ref={canvasRef} className="absolute inset-0 h-full w-full object-contain"/><div className="pointer-events-none absolute left-2 top-2 rounded-full bg-white/90 px-2 py-1 text-xs font-bold">{mode==='add'?'+ Lisää alue':'− Poista alue'}</div></div>{viewMode==='compare'&&<input className="mt-3 w-full" type="range" min="0" max="100" value={compareAt} onChange={e=>setCompareAt(Number(e.target.value))}/>}<div className="mt-3 flex flex-wrap gap-2"><button className={viewMode==='before'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('before')}>Ennen</button><button className={viewMode==='after'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('after')}>Jälkeen</button><button className={viewMode==='compare'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('compare')}>Vertaa</button><button className="btn-outline" disabled={historyIndex<=0} onClick={undo}><Undo2 className="size-4"/></button><button className="btn-outline" disabled={historyIndex>=history.length-1} onClick={redo}><Redo2 className="size-4"/></button></div></>}
        <input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>loadFile(e.target.files?.[0])}/><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>loadFile(e.target.files?.[0])}/>
      </div>
      <aside className="space-y-3"><div className="card p-4"><div className="flex items-center justify-between"><h2 className="font-bold text-navy-950">Pinnat</h2><button className="btn-outline px-3 py-2" onClick={addSurface}><Plus className="size-4"/> Pinta</button></div><div className="mt-3 space-y-2">{masks.map(m=><div key={m.id} className={`flex items-center gap-2 rounded-xl border p-2 ${m.id===activeId?'border-orange-400 bg-orange-50':'border-navy-100 bg-white'}`}><button className="min-w-0 flex-1 text-left" onClick={()=>setActiveId(m.id)}><span className="block truncate text-sm font-bold">{m.name}</span><span className="text-xs text-navy-500">{Math.round(maskCoverage(m)*100)} % kuvasta</span></button><span className="size-6 rounded-full border" style={{backgroundColor:m.color}}/><button onClick={()=>toggleVisible(m.id)} aria-label="Näytä/piilota">{m.visible?<Eye className="size-4"/>:<EyeOff className="size-4"/>}</button></div>)}</div>{active&&<button className="mt-3 text-sm font-semibold text-red-600" onClick={removeSurface}>Poista valittu pinta</button>}</div>
        <div className="card p-4"><h2 className="font-bold">Rajojen korjaus</h2><div className="mt-3 grid grid-cols-2 gap-2"><button className={mode==='add'?'btn-primary':'btn-outline'} onClick={()=>setMode('add')}><Plus className="size-4"/> Lisää alue</button><button className={mode==='remove'?'btn-primary':'btn-outline'} onClick={()=>setMode('remove')}><Minus className="size-4"/> Poista alue</button></div><label className="mt-3 block text-sm font-semibold">Työkalun koko {brushSize}px<input className="mt-1 w-full" type="range" min="8" max="100" value={brushSize} onChange={e=>setBrushSize(Number(e.target.value))}/></label><button className="btn-outline mt-3 w-full" onClick={smartFill}>✨ Täytä pinta</button><p className="mt-2 text-xs text-navy-500">{semanticStatus}</p></div>
        <div className="card p-4"><h2 className="font-bold">Väri</h2><div className="mt-3 grid grid-cols-6 gap-2">{palette.map(c=><button key={c} className={`aspect-square rounded-full border-2 ${color===c?'border-orange-500':'border-white'}`} style={{backgroundColor:c}} onClick={()=>setActiveColor(c)} aria-label={`Väri ${c}`}/>)}</div><div className="mt-3 flex gap-2"><input type="color" value={color} onChange={e=>setActiveColor(e.target.value)} className="h-10 w-14"/><input value={color} onChange={e=>/^#[0-9a-fA-F]{6}$/.test(e.target.value)&&setActiveColor(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-3 font-mono text-sm"/></div></div>
        <div className="card p-4"><div className="grid grid-cols-2 gap-2"><button className="btn-outline" onClick={()=>download('jpg')}><Download className="size-4"/> JPG</button><button className="btn-outline" onClick={()=>download('png')}><Download className="size-4"/> PNG</button></div><button className="btn-outline mt-2 w-full" onClick={reset}><RotateCcw className="size-4"/> Aloita pinnat alusta</button></div>
        <div className="rounded-xl bg-navy-950 p-3 text-sm text-white"><strong>VäriKamu:</strong> {status}</div>
      </aside>
    </div>
  </div></section>;
}
