import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { selectSurfaceFromCanvas } from '@/lib/smartSurfaceFill';
import { Camera, Download, Eraser, Maximize2, Redo2, RotateCcw, Sparkles, Undo2, Upload, ZoomIn, ZoomOut } from 'lucide-react';

type Point={x:number;y:number};
type Tool='wipe'|'smart'|'eraser';
type ViewMode='after'|'before'|'compare';
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));

export function UniversalCleaningStudioPage(){
  const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLImageElement>(null),effectRef=useRef<HTMLCanvasElement>(null),sourceRef=useRef<HTMLCanvasElement|null>(null),preStrokeRef=useRef<HTMLCanvasElement|null>(null),stageRef=useRef<HTMLDivElement>(null);
  const drawingRef=useRef(false),lastRef=useRef<Point|null>(null),strokeRef=useRef<Point[]>([]);
  const [imageUrl,setImageUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('wipe'),[brushSize,setBrushSize]=useState(34),[tolerance,setTolerance]=useState(58),[edgeLock,setEdgeLock]=useState(68),[strength,setStrength]=useState(72),[autoFill,setAutoFill]=useState(true),[history,setHistory]=useState<string[]>([]),[historyIndex,setHistoryIndex]=useState(-1),[zoom,setZoom]=useState(1),[viewMode,setViewMode]=useState<ViewMode>('after'),[compareAt,setCompareAt]=useState(50),[message,setMessage]=useState('Pyyhi pieni osa pinnasta. SiivousKamu yrittää tunnistaa koko saman pinnan ja näyttää puhdistetun esikatselun.');

  const loadFile=(file?:File)=>{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024)return;if(imageUrl?.startsWith('blob:'))URL.revokeObjectURL(imageUrl);setImageUrl(URL.createObjectURL(file));setHistory([]);setHistoryIndex(-1);setZoom(1);setViewMode('after');setMessage('Pyyhi pieni viiva ikkunaan, lattiaan, kaapin oveen tai muuhun pintaan. Viiva toimii vihjeenä.');};
  const onImageLoad=()=>{const img=imageRef.current,c=effectRef.current;if(!img||!c)return;const longest=Math.max(img.naturalWidth,img.naturalHeight),scale=Math.min(1,1400/longest),width=Math.max(1,Math.round(img.naturalWidth*scale)),height=Math.max(1,Math.round(img.naturalHeight*scale));setSize({width,height});c.width=width;c.height=height;c.getContext('2d')?.clearRect(0,0,width,height);const s=document.createElement('canvas');s.width=width;s.height=height;s.getContext('2d')?.drawImage(img,0,0,width,height);sourceRef.current=s;const first=c.toDataURL('image/png');setHistory([first]);setHistoryIndex(0);};
  const pointFromEvent=(e:ReactPointerEvent<HTMLDivElement>)=>{const stage=stageRef.current;if(!stage||!size.width)return null;const r=stage.getBoundingClientRect();return{x:clamp(((e.clientX-r.left)/r.width)*size.width,0,size.width-1),y:clamp(((e.clientY-r.top)/r.height)*size.height,0,size.height-1)};};
  const snapshot=()=>{const c=effectRef.current;if(!c)return;const copy=document.createElement('canvas');copy.width=c.width;copy.height=c.height;copy.getContext('2d')?.drawImage(c,0,0);preStrokeRef.current=copy;};
  const restorePre=()=>{const c=effectRef.current,s=preStrokeRef.current;if(!c||!s)return;const ctx=c.getContext('2d');ctx?.clearRect(0,0,c.width,c.height);ctx?.drawImage(s,0,0);};
  const commit=()=>{const c=effectRef.current;if(!c)return;const next=[...history.slice(0,historyIndex+1),c.toDataURL('image/png')].slice(-30);setHistory(next);setHistoryIndex(next.length-1);};
  const drawGuide=(a:Point,b:Point)=>{const ctx=effectRef.current?.getContext('2d');if(!ctx)return;ctx.save();ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=tool==='eraser'?'#000':'rgba(20,184,166,.82)';ctx.lineWidth=brushSize;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore();};

  const smartClean=(rawSeeds:Point[],save=true)=>{const source=sourceRef.current,target=effectRef.current,sourceCtx=source?.getContext('2d'),targetCtx=target?.getContext('2d');if(!source||!target||!sourceCtx||!targetCtx||!rawSeeds.length)return;const sharedSelection = selectSurfaceFromCanvas(source, rawSeeds, { tolerance, edgeLock });if (!sharedSelection) return;if (sharedSelection.stopped) { setMessage('Valinta pysäytettiin turvallisuussyistä. Lisää Rajojen suojausta ja kokeile pienempää aluetta.'); return; }const w=source.width,h=source.height,img=sourceCtx.getImageData(0,0,w,h),data=img.data,total=w*h,stride=Math.max(1,Math.floor(rawSeeds.length/28)),seeds=rawSeeds.filter((_,i)=>i%stride===0).slice(0,32),refs=seeds.map(s=>{const x=clamp(Math.floor(s.x),0,w-1),y=clamp(Math.floor(s.y),0,h-1),p=(y*w+x)*4;return{index:y*w+x,r:data[p],g:data[p+1],b:data[p+2]};});
    const lum=(i:number)=>{const p=i*4;return data[p]*.299+data[p+1]*.587+data[p+2]*.114;},dist=(a:number,b:number)=>{const pa=a*4,pb=b*4,dr=data[pa]-data[pb],dg=data[pa+1]-data[pb+1],db=data[pa+2]-data[pb+2];return Math.sqrt(dr*dr+dg*dg+db*db);},refDist=(i:number)=>{const p=i*4;let best=999;for(const r of refs){const dr=data[p]-r.r,dg=data[p+1]-r.g,db=data[p+2]-r.b;best=Math.min(best,Math.sqrt(dr*dr+dg*dg+db*db));}return best;},edge=(a:number,b:number)=>Math.max(Math.abs(lum(a)-lum(b)),dist(a,b)*.55);
    const seen=new Uint8Array(total),mask=new Uint8Array(total),q=new Int32Array(total);let head=0,tail=0,count=0;refs.forEach(r=>{if(!seen[r.index]){seen[r.index]=1;q[tail++]=r.index;}});const edgeThreshold=clamp(78-edgeLock*.68,18,55),direct=tolerance*1.65,gradual=20+tolerance*.34,far=tolerance*3.1,safety=Math.floor(total*.72);
    while(head<tail&&count<safety){const i=q[head++];mask[i]=1;count++;const x=i%w,y=Math.floor(i/w);const visit=(n:number)=>{if(seen[n])return;seen[n]=1;if(edge(i,n)>edgeThreshold)return;const rd=refDist(n),ld=dist(i,n);if(rd<=direct||(ld<=gradual&&rd<=far))q[tail++]=n;};if(x>0)visit(i-1);if(x<w-1)visit(i+1);if(y>0)visit(i-w);if(y<h-1)visit(i+w);}
    if(count<Math.max(120,Math.round(total*.0004))){setMessage('Pintaa ei löytynyt riittävästi. Pyyhi hieman pidempi viiva pinnan keskelle tai vähennä Rajojen suojausta.');return;}if(count>=safety){setMessage('Valinta levisi liian suureksi ja pysäytettiin. Lisää Rajojen suojausta ja kokeile uudelleen.');return;}
    const out=targetCtx.createImageData(w,h);for(let i=0;i<mask.length;i++)if(mask[i]){const p=i*4,r=data[p],g=data[p+1],b=data[p+2],l=(r+g+b)/3,mix=strength/100;out.data[p]=clamp(Math.round(r+(255-r)*.18*mix+(l-r)*.08*mix),0,255);out.data[p+1]=clamp(Math.round(g+(255-g)*.18*mix+(l-g)*.08*mix),0,255);out.data[p+2]=clamp(Math.round(b+(255-b)*.18*mix+(l-b)*.08*mix),0,255);out.data[p+3]=220;}
    const overlay=document.createElement('canvas');overlay.width=w;overlay.height=h;overlay.getContext('2d')?.putImageData(out,0,0);targetCtx.drawImage(overlay,0,0);if(save)commit();setMessage(`Pinta täydennettiin automaattisesti (${Math.round(count/1000)}k px). Esikatselu näyttää vain valitun pinnan puhtaampana; ympäristö säilyy ennallaan.`);};

  const down=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!imageUrl||viewMode!=='after')return;e.currentTarget.setPointerCapture(e.pointerId);const p=pointFromEvent(e);if(!p)return;if(tool==='smart'){smartClean([p],true);return;}snapshot();drawingRef.current=true;lastRef.current=p;strokeRef.current=[p];drawGuide(p,p);};
  const move=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawingRef.current||!lastRef.current)return;const p=pointFromEvent(e);if(!p)return;drawGuide(lastRef.current,p);const prev=strokeRef.current[strokeRef.current.length-1];if(!prev||Math.hypot(p.x-prev.x,p.y-prev.y)>Math.max(6,brushSize*.22))strokeRef.current.push(p);lastRef.current=p;};
  const up=()=>{if(!drawingRef.current)return;drawingRef.current=false;lastRef.current=null;const seeds=strokeRef.current;strokeRef.current=[];if(tool==='wipe'&&autoFill&&seeds.length){restorePre();smartClean(seeds,true);}else commit();};
  const restore=(i:number)=>{const c=effectRef.current,frame=history[i];if(!c||!frame)return;const ctx=c.getContext('2d'),img=new Image();img.onload=()=>{ctx?.clearRect(0,0,c.width,c.height);ctx?.drawImage(img,0,0);setHistoryIndex(i);};img.src=frame;};
  const reset=()=>{const c=effectRef.current;if(!c)return;c.getContext('2d')?.clearRect(0,0,c.width,c.height);commit();};
  const download=()=>{const img=imageRef.current,effect=effectRef.current;if(!img||!effect||!size.width)return;const out=document.createElement('canvas');out.width=size.width;out.height=size.height;const ctx=out.getContext('2d');if(!ctx)return;ctx.drawImage(img,0,0,size.width,size.height);ctx.drawImage(effect,0,0);ctx.fillStyle='rgba(255,255,255,.82)';ctx.fillRect(12,size.height-34,Math.min(330,size.width-24),22);ctx.fillStyle='#172033';ctx.font='12px sans-serif';ctx.fillText('SiivousKamu · maalausmultivari.fi',20,size.height-19);const a=document.createElement('a');a.download=`siivouskamu-${Date.now()}.jpg`;a.href=out.toDataURL('image/jpeg',.92);a.click();};
  const ratio=size.width&&size.height?size.width/size.height:4/3,stageWidth=size.width?`min(100%, calc(58dvh * ${ratio}))`:'100%',canvasStyle=useMemo(()=>viewMode==='before'?{display:'none'}:viewMode==='compare'?{clipPath:`inset(0 ${100-compareAt}% 0 0)`}:undefined,[viewMode,compareAt]);

  return <section className="min-h-screen w-full overflow-x-hidden bg-navy-50 px-2 py-3 sm:px-3 sm:py-4"><div className="container-base w-full max-w-6xl"><div className="mb-3"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">SiivousKamu</p><h1 className="font-display text-xl font-extrabold text-navy-950 sm:text-2xl">Pyyhi vähän – SiivousKamu täydentää pinnan</h1></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]">
    <div className="card min-w-0 overflow-hidden p-2 sm:p-4">{!imageUrl?<div className="grid min-h-[46vh] place-items-center rounded-2xl border-2 border-dashed border-navy-200 bg-white p-5 text-center"><div><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-4 text-xl font-bold">Ota kuva tai lataa kuva</h2><p className="mt-2 text-sm text-navy-600">Ikkuna, lattia, kaappi, taso, peili, liesi, allas tai muu puhdistettava pinta.</p><div className="mt-5 flex justify-center gap-3"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/>Ota kuva</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Lataa kuva</button></div></div></div>:<><div className="w-full overflow-auto rounded-2xl bg-navy-950 p-1" style={{maxHeight:'64dvh'}}><div className="flex min-h-[260px] items-center justify-center"><div ref={stageRef} className="relative shrink-0 overflow-hidden rounded-xl bg-black" style={{width:stageWidth,aspectRatio:`${size.width}/${size.height}`,maxWidth:'100%',transform:`scale(${zoom})`,transformOrigin:'center',touchAction:'none'}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><img ref={imageRef} src={imageUrl} onLoad={onImageLoad} draggable={false} className="absolute inset-0 h-full w-full select-none object-fill"/><canvas ref={effectRef} className="absolute inset-0 h-full w-full" style={canvasStyle}/>{viewMode==='compare'&&<div className="pointer-events-none absolute inset-y-0 z-20 w-0.5 bg-white" style={{left:`${compareAt}%`}}/>}</div></div></div><div className="mt-2 flex gap-2"><button className="btn-outline" onClick={()=>setZoom(z=>Math.max(1,z-.25))}><ZoomOut className="size-4"/>−</button><button className="btn-outline" onClick={()=>setZoom(1)}><Maximize2 className="size-4"/>Sovita</button><button className="btn-outline" onClick={()=>setZoom(z=>Math.min(2.5,z+.25))}><ZoomIn className="size-4"/>+</button></div><div className="mt-3 grid grid-cols-3 gap-2"><button className={viewMode==='before'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('before')}>Ennen</button><button className={viewMode==='after'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('after')}>Jälkeen</button><button className={viewMode==='compare'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('compare')}>Vertaa</button></div>{viewMode==='compare'&&<input className="mt-3 w-full accent-orange-500" type="range" min="5" max="95" value={compareAt} onChange={e=>setCompareAt(Number(e.target.value))}/>}</>}
    <input ref={fileRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>loadFile(e.target.files?.[0])}/><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>loadFile(e.target.files?.[0])}/>{imageUrl&&<div className="mt-2 flex flex-wrap gap-2"><button className="btn-outline" onClick={()=>historyIndex>0&&restore(historyIndex-1)} disabled={historyIndex<=0}><Undo2 className="size-4"/>Kumoa</button><button className="btn-outline" onClick={()=>historyIndex<history.length-1&&restore(historyIndex+1)} disabled={historyIndex>=history.length-1}><Redo2 className="size-4"/>Tee uudelleen</button><button className="btn-outline" onClick={reset}><RotateCcw className="size-4"/>Tyhjennä</button></div>}</div>
    <aside className="space-y-4"><div className="card p-4"><h2 className="font-bold">1. Työkalu</h2><div className="mt-3 grid grid-cols-2 gap-2"><button className={tool==='wipe'?'btn-primary':'btn-outline'} onClick={()=>{setTool('wipe');setViewMode('after');}}>🧽 Pyyhi</button><button className={tool==='smart'?'btn-primary':'btn-outline'} onClick={()=>{setTool('smart');setViewMode('after');}}><Sparkles className="size-4"/>Täytä napautus</button><button className={tool==='eraser'?'btn-primary':'btn-outline'} onClick={()=>{setTool('eraser');setViewMode('after');}}><Eraser className="size-4"/>Pyyhin</button></div><label className="mt-4 flex items-center justify-between rounded-xl bg-orange-50 px-3 py-3 text-sm font-bold"><span>✨ Täydennä pinta automaattisesti</span><input type="checkbox" checked={autoFill} onChange={e=>setAutoFill(e.target.checked)} className="size-5 accent-orange-500"/></label><p className="mt-3 text-xs leading-5 text-navy-600">Pyyhintäviiva toimii vain vihjeenä. SiivousKamu yrittää täydentää saman pinnan rajojen sisällä.</p></div><div className="card p-4"><label className="text-sm font-bold">Pyyhkimen koko {brushSize}px<input className="mt-2 w-full accent-orange-500" type="range" min="10" max="100" value={brushSize} onChange={e=>setBrushSize(Number(e.target.value))}/></label><label className="mt-4 block text-sm font-bold">Pinnan vaihtelu {tolerance}<input className="mt-2 w-full accent-orange-500" type="range" min="30" max="100" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></label><label className="mt-4 block text-sm font-bold">Rajojen suojaus {edgeLock}%<input className="mt-2 w-full accent-orange-500" type="range" min="35" max="85" value={edgeLock} onChange={e=>setEdgeLock(Number(e.target.value))}/></label><label className="mt-4 block text-sm font-bold">Puhdistuksen voimakkuus {strength}%<input className="mt-2 w-full accent-orange-500" type="range" min="35" max="100" value={strength} onChange={e=>setStrength(Number(e.target.value))}/></label></div><div className="card p-4"><p className="text-sm leading-6 text-navy-700">{message}</p><button className="btn-primary mt-3 w-full" onClick={download} disabled={!imageUrl}><Download className="size-4"/>Lataa JPG</button><p className="mt-2 text-[11px] text-navy-500">Esikatselu on visuaalinen suunnitteluapu, ei lupaus lopullisesta puhdistustuloksesta.</p></div></aside>
  </div></div></section>;
}
