import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Camera, Download, Eraser, HelpCircle, Maximize2, Paintbrush, PaintRoller, Redo2, RotateCcw, Shield, Sparkles, Undo2, Upload, ZoomIn, ZoomOut } from 'lucide-react';
import { CanvasPipeline } from '@/lib/engine/CanvasPipeline';
import { MaskLayer } from '@/lib/engine/MaskLayer';
import { SegmentationProvider, mergeManualAndSmart } from '@/lib/ai/SegmentationProvider';

type Point={x:number;y:number};
type Tool='brush'|'corner'|'roller'|'eraser'|'cover'|'coverEraser'|'scraper'|'putty'|'sand'|'line'|'rect'|'circle';
type ViewMode='before'|'after'|'compare';
type Snapshot={manual:number[];smart:number[];protect:number[];prep:string};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const palette=['#F2EFE6','#D8C9B5','#C9CBC8','#A7B19B','#9FB4C3','#B86F52','#496255','#45494B','#1D2022','#FF6B9D','#6C5CE7','#00B894'];
const brushes=[{label:'0.5 cm',px:6},{label:'1 cm',px:11},{label:'2 cm',px:18},{label:'3 cm',px:26},{label:'5 cm',px:38},{label:'7 cm',px:54},{label:'10 cm',px:72}];
const covers=[{label:'1 cm',px:12},{label:'2 cm',px:22},{label:'5 cm',px:42},{label:'10 cm',px:76}];
const rgb=(hex:string):[number,number,number]=>{const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]};
const segmentation=new SegmentationProvider();
const paintCursor='url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%2236%22%20height%3D%2236%22%3E%3Ctext%20x%3D%222%22%20y%3D%2227%22%20font-size%3D%2225%22%3E%F0%9F%96%90%EF%B8%8F%F0%9F%96%8C%EF%B8%8F%3C/text%3E%3C/svg%3E") 4 28, crosshair';

export function VarikamuEnterpriseStudioPage(){
  const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLImageElement>(null),stageRef=useRef<HTMLDivElement>(null),finalRef=useRef<HTMLCanvasElement>(null),protectCanvasRef=useRef<HTMLCanvasElement>(null),sourceRef=useRef<HTMLCanvasElement|null>(null),prepRef=useRef<HTMLCanvasElement|null>(null),manualRef=useRef<MaskLayer|null>(null),smartRef=useRef<MaskLayer|null>(null),protectRef=useRef<MaskLayer|null>(null),drawingRef=useRef(false),lastRef=useRef<Point|null>(null),startRef=useRef<Point|null>(null),strokeRef=useRef<Point[]>([]),generationRef=useRef(0);
  const[imageUrl,setImageUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('brush'),[color,setColor]=useState('#9FB4C3'),[brushSize,setBrushSize]=useState(38),[coverSize,setCoverSize]=useState(22),[opacity,setOpacity]=useState(1),[passes,setPasses]=useState<1|2|3|4>(4),[smart,setSmart]=useState(true),[stabilizer,setStabilizer]=useState(76),[tolerance,setTolerance]=useState(32),[showProtection,setShowProtection]=useState(true),[smartBusy,setSmartBusy]=useState(false),[history,setHistory]=useState<Snapshot[]>([]),[historyIndex,setHistoryIndex]=useState(-1),[viewMode,setViewMode]=useState<ViewMode>('after'),[compareAt,setCompareAt]=useState(50),[zoom,setZoom]=useState(1),[showGuide,setShowGuide]=useState(true),[message,setMessage]=useState('Suojaus estää nyt pysyvästi maalin ja valmistelutyöt. Voit myös poistaa vain osan suojauksesta.');
  const loadFile=(file?:File)=>{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024)return;if(imageUrl?.startsWith('blob:'))URL.revokeObjectURL(imageUrl);setImageUrl(URL.createObjectURL(file));setHistory([]);setHistoryIndex(-1);setZoom(1);setViewMode('after')};
  const onImageLoad=()=>{const img=imageRef.current,final=finalRef.current,pc=protectCanvasRef.current;if(!img||!final||!pc)return;const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),width=Math.max(1,Math.round(img.naturalWidth*scale)),height=Math.max(1,Math.round(img.naturalHeight*scale));setSize({width,height});final.width=width;final.height=height;pc.width=width;pc.height=height;const s=document.createElement('canvas');s.width=width;s.height=height;s.getContext('2d')?.drawImage(img,0,0,width,height);sourceRef.current=s;const prep=document.createElement('canvas');prep.width=width;prep.height=height;prepRef.current=prep;manualRef.current=new MaskLayer(width,height);smartRef.current=new MaskLayer(width,height);protectRef.current=new MaskLayer(width,height);renderCurrent();window.setTimeout(()=>commit(),0)};
  const point=(e:ReactPointerEvent<HTMLDivElement>)=>{const stage=stageRef.current;if(!stage||!size.width)return null;const r=stage.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*size.width,0,size.width-1),y:clamp((e.clientY-r.top)/r.height*size.height,0,size.height-1)}};
  const smooth=(a:Point,b:Point)=>{const s=clamp(stabilizer/100,0,.92);return{x:a.x*s+b.x*(1-s),y:a.y*s+b.y*(1-s)}};
  const snap=(a:Point,b:Point)=>{const dx=b.x-a.x,dy=b.y-a.y,d=Math.abs(Math.atan2(dy,dx)*180/Math.PI);if(d<12||d>168)return{x:b.x,y:a.y};if(Math.abs(d-90)<12)return{x:a.x,y:b.y};return b};
  const canvasMask=(draw:(ctx:CanvasRenderingContext2D)=>void)=>{const c=document.createElement('canvas');c.width=size.width;c.height=size.height;const ctx=c.getContext('2d'),m=new MaskLayer(size.width,size.height);if(!ctx)return m;ctx.strokeStyle='#fff';ctx.fillStyle='#fff';draw(ctx);const d=ctx.getImageData(0,0,c.width,c.height).data;for(let i=0;i<m.alpha.length;i++)m.alpha[i]=d[i*4+3];return m};
  const lineMask=(a:Point,b:Point,width:number,square=false)=>canvasMask(ctx=>{ctx.lineWidth=width;ctx.lineCap=square?'square':'round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()});
  const shapeMask=(a:Point,b:Point,kind:'line'|'rect'|'circle')=>canvasMask(ctx=>{ctx.lineWidth=brushSize;ctx.lineCap='round';ctx.lineJoin='round';if(kind==='line'){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();return}if(kind==='rect'){ctx.strokeRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));return}const cx=(a.x+b.x)/2,cy=(a.y+b.y)/2,rx=Math.abs(b.x-a.x)/2,ry=Math.abs(b.y-a.y)/2;ctx.beginPath();ctx.ellipse(cx,cy,Math.max(1,rx),Math.max(1,ry),0,0,Math.PI*2);ctx.stroke()});
  const workingBase=()=>{const s=sourceRef.current,p=prepRef.current;if(!s)return null;const c=document.createElement('canvas');c.width=s.width;c.height=s.height;const x=c.getContext('2d');if(!x)return null;x.drawImage(s,0,0);if(p)x.drawImage(p,0,0);return c};
  const renderCurrent=()=>{const f=finalRef.current,m=manualRef.current,sm=smartRef.current,pr=protectRef.current,b=workingBase();if(!f||!m||!sm||!pr||!b)return;const total=mergeManualAndSmart(m,sm).subtract(pr),pipeline=new CanvasPipeline(f);pipeline.setSize({width:b.width,height:b.height});pipeline.renderBaseImage(b);pipeline.applyPaintMask(total,{tint:rgb(color),coat:passes,opacity});drawProtectionOverlay()};
  const drawProtectionOverlay=()=>{const c=protectCanvasRef.current,m=protectRef.current;if(!c||!m)return;const x=c.getContext('2d');if(!x)return;x.clearRect(0,0,c.width,c.height);const img=x.createImageData(c.width,c.height);for(let i=0;i<m.alpha.length;i++){if(!m.alpha[i])continue;const p=i*4;img.data[p]=249;img.data[p+1]=115;img.data[p+2]=22;img.data[p+3]=Math.round(m.alpha[i]*.56)}x.putImageData(img,0,0)};
  const erasePrep=(mask:MaskLayer)=>{const p=prepRef.current;if(!p)return;const x=p.getContext('2d');if(!x)return;const temp=document.createElement('canvas');temp.width=p.width;temp.height=p.height;const t=temp.getContext('2d');if(!t)return;const md=t.createImageData(p.width,p.height);for(let i=0;i<mask.alpha.length;i++){const q=i*4;md.data[q]=255;md.data[q+1]=255;md.data[q+2]=255;md.data[q+3]=mask.alpha[i]}t.putImageData(md,0,0);x.save();x.globalCompositeOperation='destination-out';x.drawImage(temp,0,0);x.restore()};
  const applyPrep=(raw:MaskLayer,mode:'scraper'|'putty'|'sand')=>{const s=sourceRef.current,p=prepRef.current,protection=protectRef.current;if(!s||!p||!protection)return;const mask=raw.subtract(protection),px=p.getContext('2d');if(!px)return;const selection=document.createElement('canvas');selection.width=s.width;selection.height=s.height;const mx=selection.getContext('2d');if(!mx)return;const md=mx.createImageData(s.width,s.height);for(let i=0;i<mask.alpha.length;i++){const q=i*4;md.data[q]=255;md.data[q+1]=255;md.data[q+2]=255;md.data[q+3]=mask.alpha[i]}mx.putImageData(md,0,0);const effect=document.createElement('canvas');effect.width=s.width;effect.height=s.height;const ex=effect.getContext('2d');if(!ex)return;ex.save();ex.filter=mode==='scraper'?'blur(1.15px) contrast(90%) saturate(82%)':mode==='putty'?'blur(3.4px) contrast(88%) saturate(62%) brightness(1.12)':'blur(2px) contrast(92%) saturate(90%)';ex.drawImage(s,0,0);ex.restore();if(mode==='putty'){ex.save();ex.globalCompositeOperation='source-atop';ex.fillStyle='rgba(228,220,207,.48)';ex.fillRect(0,0,effect.width,effect.height);ex.restore()}ex.globalCompositeOperation='destination-in';ex.drawImage(selection,0,0);px.drawImage(effect,0,0);renderCurrent()};
  const applyManual=(a:Point,b:Point)=>{const m=manualRef.current,sm=smartRef.current,p=protectRef.current;if(!m||!sm||!p)return;const width=tool==='roller'?brushSize*2.1:tool==='corner'?Math.max(4,brushSize*.55):brushSize,mask=lineMask(a,b,width,tool==='roller'||tool==='corner');if(tool==='eraser'){manualRef.current=m.subtract(mask);smartRef.current=sm.subtract(mask);renderCurrent();return}if(tool==='scraper'||tool==='putty'||tool==='sand'){applyPrep(mask,tool);return}manualRef.current=m.union(mask.subtract(p));renderCurrent()};
  const applyCover=(a:Point,b:Point,erase=false)=>{const p=protectRef.current,m=manualRef.current,sm=smartRef.current;if(!p||!m||!sm)return;const mask=lineMask(a,b,coverSize);if(erase){protectRef.current=p.subtract(mask);renderCurrent();return}protectRef.current=p.union(mask);manualRef.current=m.subtract(mask);smartRef.current=sm.subtract(mask);erasePrep(mask);renderCurrent()};
  const applyShape=(a:Point,b:Point,kind:'line'|'rect'|'circle')=>{const m=manualRef.current,p=protectRef.current;if(!m||!p)return;manualRef.current=m.union(shapeMask(a,b,kind).subtract(p));renderCurrent()};
  const smartFill=async(seed:Point)=>{const s=sourceRef.current,m=manualRef.current,old=smartRef.current,p=protectRef.current;if(!s||!m||!old||!p)return;const x=s.getContext('2d');if(!x)return;const image=x.getImageData(0,0,s.width,s.height),gen=++generationRef.current;setSmartBusy(true);try{const result=await segmentation.segment({imageId:`${s.width}x${s.height}:${imageUrl??'local'}`,image,point:seed,tolerance});if(gen!==generationRef.current)return;const safe=result.mask.subtract(p),coverage=safe.alpha.reduce((n,a)=>n+(a>0?1:0),0)/(safe.width*safe.height);if(coverage>.38){smartRef.current=old;setMessage('Smart hylättiin: alue oli liian suuri. Oma maalaus säilyi.');return}smartRef.current=mergeManualAndSmart(m,safe).subtract(m);renderCurrent();setMessage(result.source==='remote-sam'?'Smart tunnisti pinnan.':'Paikallinen Smart täydensi vain turvallisen alueen.')}catch{setMessage('Smart epäonnistui, mutta oma maalaus säilyi.')}finally{if(gen===generationRef.current)setSmartBusy(false)}};
  const down=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!imageUrl||viewMode!=='after')return;e.preventDefault();const p=point(e);if(!p)return;e.currentTarget.setPointerCapture?.(e.pointerId);drawingRef.current=true;lastRef.current=p;startRef.current=p;strokeRef.current=[p]};
  const move=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawingRef.current||!lastRef.current)return;e.preventDefault();const raw=point(e);if(!raw)return;const p=smooth(lastRef.current,raw);strokeRef.current.push(p);if(!['cover','coverEraser','line','rect','circle'].includes(tool))applyManual(lastRef.current,p);lastRef.current=p};
  const up=(e?:ReactPointerEvent<HTMLDivElement>)=>{e?.preventDefault();if(!drawingRef.current)return;drawingRef.current=false;const start=startRef.current,last=lastRef.current,pts=strokeRef.current;lastRef.current=null;startRef.current=null;if(start&&last&&(tool==='cover'||tool==='coverEraser')){applyCover(start,snap(start,last),tool==='coverEraser');commit();setMessage(tool==='cover'?'Suoja lisättiin ja alla oleva maali/kitti poistettiin pysyvästi.':'Vain piirretty osa suojauksesta poistettiin.');return}if(start&&last&&(tool==='line'||tool==='rect'||tool==='circle')){applyShape(start,last,tool);commit();setMessage('Geometrinen maalausalue lisättiin.');return}commit();if(smart&&(tool==='brush'||tool==='corner'||tool==='roller')&&pts.length)void smartFill(pts[Math.floor(pts.length/2)])};
  const snapshot=():Snapshot|null=>{const m=manualRef.current,s=smartRef.current,p=protectRef.current,prep=prepRef.current;if(!m||!s||!p||!prep)return null;return{manual:m.toRle(),smart:s.toRle(),protect:p.toRle(),prep:prep.toDataURL('image/png')}};
  const commit=()=>{const snap=snapshot();if(!snap)return;const next=[...history.slice(0,historyIndex+1),snap].slice(-30);setHistory(next);setHistoryIndex(next.length-1)};
  const restore=(i:number)=>{const snap=history[i],prep=prepRef.current;if(!snap||!size.width||!prep)return;manualRef.current=MaskLayer.fromRle(size.width,size.height,snap.manual);smartRef.current=MaskLayer.fromRle(size.width,size.height,snap.smart);protectRef.current=MaskLayer.fromRle(size.width,size.height,snap.protect);const img=new Image();img.onload=()=>{const c=prep.getContext('2d');c?.clearRect(0,0,prep.width,prep.height);c?.drawImage(img,0,0);setHistoryIndex(i);renderCurrent()};img.src=snap.prep};
  const reset=()=>{manualRef.current?.clear();smartRef.current?.clear();prepRef.current?.getContext('2d')?.clearRect(0,0,size.width,size.height);renderCurrent();commit()};
  const clearProtection=()=>{protectRef.current?.clear();renderCurrent();commit();setMessage('Kaikki suojaus poistettiin. Käytä “Poista suojaa” poistaaksesi vain osan.')};
  const download=(type:'png'|'jpg')=>{const c=finalRef.current;if(!c)return;const a=document.createElement('a');a.download=`varikamu-${Date.now()}.${type}`;a.href=type==='jpg'?c.toDataURL('image/jpeg',.94):c.toDataURL('image/png');a.click()};
  const ratio=size.width&&size.height?size.width/size.height:4/3,stageWidth=size.width?`min(100%, calc(58dvh * ${ratio}))`:'100%',finalStyle=useMemo(()=>viewMode==='before'?{display:'none'}:viewMode==='compare'?{clipPath:`inset(0 ${100-compareAt}% 0 0)`}:undefined,[viewMode,compareAt]);
  const isPaintTool=['brush','corner','roller','line','rect','circle'].includes(tool);
  return <section className="min-h-screen w-full overflow-x-hidden bg-navy-50 px-2 py-3"><div className="container-base w-full max-w-6xl">
    <div className="mb-3 flex items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase text-orange-600">VäriKamu Enterprise</p><h1 className="font-display text-xl font-extrabold text-navy-950 sm:text-2xl">Valmistele, suojaa ja maalaa jopa neljällä kerroksella</h1></div><button className="btn-outline" onClick={()=>setShowGuide(v=>!v)}><HelpCircle className="size-4"/>Ohje</button></div>
    {showGuide&&<div className="mb-4 rounded-2xl border border-orange-200 bg-orange-50 p-4 text-sm"><strong>📷 Kuva → 🪚 Kaavi → 🧱 Kittaa → 🧽 Hio → 🛡️ Suojaa → 🎨 Maalaa ×4 → 👁 Tarkista</strong></div>}
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="card min-w-0 overflow-hidden p-2 sm:p-4">
      {!imageUrl?<div className="grid min-h-[46vh] place-items-center rounded-2xl border-2 border-dashed border-navy-200 bg-white p-5 text-center"><div><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-4 text-xl font-bold">Ota kuva tai lataa kuva</h2><div className="mt-5 flex justify-center gap-3"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/>Ota kuva</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Lataa kuva</button></div></div></div>:<><div className="w-full overflow-hidden rounded-2xl bg-navy-950 p-1"><div className="flex min-h-[260px] items-center justify-center overflow-hidden"><div ref={stageRef} className="relative shrink-0 overflow-hidden rounded-xl bg-black" style={{width:stageWidth,aspectRatio:`${size.width}/${size.height}`,maxWidth:'100%',transform:`scale(${zoom})`,touchAction:'none',cursor:isPaintTool?paintCursor:'crosshair'}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><img ref={imageRef} src={imageUrl} onLoad={onImageLoad} draggable={false} className="pointer-events-none absolute inset-0 h-full w-full object-fill"/><canvas ref={finalRef} className="pointer-events-none absolute inset-0 h-full w-full" style={finalStyle}/><canvas ref={protectCanvasRef} className={`pointer-events-none absolute inset-0 h-full w-full ${showProtection?'opacity-100':'opacity-0'}`}/></div></div></div><div className="mt-2 flex gap-2"><button className="btn-outline" onClick={()=>setZoom(z=>Math.max(1,z-.25))}><ZoomOut className="size-4"/>−</button><button className="btn-outline" onClick={()=>setZoom(1)}><Maximize2 className="size-4"/>Sovita</button><button className="btn-outline" onClick={()=>setZoom(z=>Math.min(2.5,z+.25))}><ZoomIn className="size-4"/>+</button></div><div className="mt-3 grid grid-cols-3 gap-2"><button className={viewMode==='before'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('before')}>Ennen</button><button className={viewMode==='after'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('after')}>Jälkeen</button><button className={viewMode==='compare'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('compare')}>Vertaa</button></div>{viewMode==='compare'&&<input className="mt-3 w-full" type="range" min="5" max="95" value={compareAt} onChange={e=>setCompareAt(Number(e.target.value))}/>}</>}
      <input ref={fileRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>loadFile(e.target.files?.[0])}/><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>loadFile(e.target.files?.[0])}/>
      {imageUrl&&<div className="mt-2 flex flex-wrap gap-2"><button className="btn-outline" onClick={()=>historyIndex>0&&restore(historyIndex-1)} disabled={historyIndex<=0}><Undo2 className="size-4"/>Kumoa</button><button className="btn-outline" onClick={()=>historyIndex<history.length-1&&restore(historyIndex+1)} disabled={historyIndex>=history.length-1}><Redo2 className="size-4"/>Tee uudelleen</button><button className="btn-outline" onClick={reset}><RotateCcw className="size-4"/>Tyhjennä</button><button className="btn-outline" onClick={()=>setShowProtection(v=>!v)}>{showProtection?'Piilota suoja':'Näytä suoja'}</button><button className="btn-outline" onClick={clearProtection}><Shield className="size-4"/>Poista kaikki suojat</button></div>}
    </div><aside className="space-y-4">
      <div className="card p-4"><h2 className="font-bold">1. Työkalu</h2><div className="mt-3 grid grid-cols-2 gap-2">{(['scraper','putty','sand','cover','coverEraser','brush','corner','roller','eraser','line','rect','circle'] as Tool[]).map(t=><button key={t} className={tool===t?'btn-primary':'btn-outline'} onClick={()=>{setTool(t);if(t==='cover'||t==='coverEraser')setShowProtection(true)}}>{t==='brush'?<><Paintbrush className="size-4"/>Sivellin</>:t==='roller'?<><PaintRoller className="size-4"/>Tela</>:t==='eraser'?<><Eraser className="size-4"/>Poista maalia</>:t==='cover'?'🛡️ Suojaa':t==='coverEraser'?'➖ Poista suojaa':t==='corner'?'◩ Kulmasivellin':t==='scraper'?'🪚 Kaavin':t==='putty'?'🧱 Kitti':t==='sand'?'🧽 Hionta':t==='line'?'／ Viiva':t==='rect'?'▭ Suorakulmio':'◯ Ympyrä'}</button>)}</div><button className="mt-3 w-full rounded-xl border border-orange-300 bg-orange-50 p-3 text-left" onClick={()=>setSmart(v=>!v)}><strong><Sparkles className="mr-1 inline size-4"/>Smart {smart?'ON':'OFF'} {smartBusy?'· tunnistaa…':''}</strong></button></div>
      {(tool==='cover'||tool==='coverEraser')&&<div className="card p-4"><h2 className="font-bold">2. Suojauksen leveys</h2><div className="mt-3 grid grid-cols-4 gap-2">{covers.map(c=><button key={c.label} className={`rounded-xl border p-2 text-xs font-bold ${coverSize===c.px?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>setCoverSize(c.px)}>{c.label}</button>)}</div><p className="mt-2 text-xs text-navy-600">“Poista suojaa” pyyhkii vain piirretyn osan, ei koko suojausta.</p></div>}
      <div className="card p-4"><h2 className="font-bold">3. Työkalun leveys</h2><div className="mt-3 grid grid-cols-4 gap-2">{brushes.map(b=><button key={b.label} className={`rounded-xl border p-2 text-xs font-bold ${brushSize===b.px?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>setBrushSize(b.px)}>{b.label}</button>)}</div></div>
      <div className="card p-4"><h2 className="font-bold">4. Väri ja peittävyys</h2><div className="mt-3 flex flex-wrap gap-2">{palette.map(c=><button key={c} aria-label={c} onClick={()=>{setColor(c);window.setTimeout(renderCurrent,0)}} className={`h-9 w-9 rounded-full border-2 ${color===c?'border-orange-500 ring-2 ring-orange-200':'border-white'}`} style={{backgroundColor:c}}/>)}<input title="Mukautettu väri" type="color" value={color} onChange={e=>{setColor(e.target.value);window.setTimeout(renderCurrent,0)}} className="h-9 w-12"/></div><label className="mt-4 block text-sm font-bold">Peittävyys {Math.round(opacity*100)} %<input className="mt-2 w-full accent-orange-500" type="range" min="0" max="100" step="1" value={Math.round(opacity*100)} onChange={e=>{setOpacity(Number(e.target.value)/100);window.setTimeout(renderCurrent,0)}}/></label><div className="mt-2 grid grid-cols-5 gap-1">{[0,25,50,75,100].map(v=><button key={v} className={`rounded-lg border px-1 py-2 text-xs font-bold ${Math.round(opacity*100)===v?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>{setOpacity(v/100);window.setTimeout(renderCurrent,0)}}>{v}%</button>)}</div><div className="mt-4 grid grid-cols-4 gap-2">{([1,2,3,4] as const).map(n=><button key={n} className={`rounded-xl border p-2 text-xs font-bold ${passes===n?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>{setPasses(n);window.setTimeout(renderCurrent,0)}}>{n===1?'1× Pohja':n===2?'2× Peitto':n===3?'3× Valmis':'4× Extra'}</button>)}</div><p className="mt-2 text-xs text-navy-600">4× Extra antaa täydellisen pigmenttipeiton. Suojattu alue pysyy alkuperäisenä myös suojauksen poistamisen jälkeen.</p><label className="mt-3 block text-sm font-bold">Käden vakautus {stabilizer}%<input className="mt-2 w-full" type="range" min="0" max="90" value={stabilizer} onChange={e=>setStabilizer(Number(e.target.value))}/></label><label className="mt-3 block text-sm font-bold">Smart-herkkyys {tolerance}<input className="mt-2 w-full" type="range" min="18" max="64" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></label></div>
      <div className="card p-4"><p className="text-sm text-navy-700">{message}</p><div className="mt-3 grid grid-cols-2 gap-2"><button className="btn-outline" onClick={()=>download('png')} disabled={!imageUrl}><Download className="size-4"/>PNG</button><button className="btn-primary" onClick={()=>download('jpg')} disabled={!imageUrl}><Download className="size-4"/>JPG</button></div></div>
    </aside></div>
  </div></section>
}
