import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Camera, Download, HelpCircle, Maximize2, Redo2, RotateCcw, Sparkles, Undo2, Upload, ZoomIn, ZoomOut } from 'lucide-react';
import { CanvasPipeline } from '@/lib/engine/CanvasPipeline';
import { MaskLayer } from '@/lib/engine/MaskLayer';
import { VarikamuMobileToolbar } from '@/components/VarikamuMobileToolbar';
import { applyWallpaper, type WallpaperKind, type WallpaperParams } from '@/lib/engine/WallpaperRenderer';
import { SegmentationProvider, mergeManualAndSmart } from '@/lib/ai/SegmentationProvider';

type Point={x:number;y:number};
type Tool='pan'|'brush'|'spray'|'corner'|'roller'|'eraser'|'cover'|'coverEraser'|'scraper'|'putty'|'sand'|'prepEraser'|'line'|'rect'|'circle'|'selectBrush'|'selectRect'|'selectCircle'|'boundary';
type ViewMode='before'|'after'|'compare';
type RollerShape='normal'|'wide'|'edge';
type SurfaceLayer={id:string;kind:'paint'|'wallpaper';mask:number[];color?:string;opacity?:number;passes?:1|2|3|4;wallpaper?:WallpaperParams};
type Snapshot={manual:number[];smart:number[];protect:number[];selection:number[];prep:string;layers:SurfaceLayer[]};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const palette=['#F2EFE6','#D8C9B5','#C9CBC8','#A7B19B','#9FB4C3','#B86F52','#496255','#45494B','#1D2022','#FF6B9D','#6C5CE7','#00B894'];
const brushes=[{label:'0.5 cm',px:6},{label:'1 cm',px:11},{label:'2 cm',px:18},{label:'3 cm',px:26},{label:'5 cm',px:38},{label:'7 cm',px:54},{label:'10 cm',px:72}];
const covers=[{label:'1 cm',px:12},{label:'2 cm',px:22},{label:'5 cm',px:42},{label:'10 cm',px:76}];
const wallpaperKinds:WallpaperKind[]=['solid','stripe','geometric','floral','concrete','wood','brick','linen'];
const wallpaperLabels:Record<WallpaperKind,string>={solid:'Yksivärinen',stripe:'Raidallinen',geometric:'Geometrinen',floral:'Kukkakuvio',concrete:'Betoni',wood:'Puu',brick:'Tiili/kivi',linen:'Pellava'};
const rgb=(hex:string):[number,number,number]=>{const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]};
const segmentation=new SegmentationProvider();
const toolLabel:Record<Tool,string>={pan:'Siirrä kuvaa',brush:'Sivellin',spray:'Maalisuihke',corner:'Kulmasivellin',roller:'Tela',eraser:'Maalipyyhin',cover:'Suojaa',coverEraser:'Poista suojaa',scraper:'Kaavin',putty:'Kitti',sand:'Hionta',prepEraser:'Poista valmistelu',line:'Suora viiva',rect:'Suorakulmio',circle:'Ympyrä',selectBrush:'Valintakynä',selectRect:'Valitse suorakulmio',selectCircle:'Valitse ympyrä',boundary:'Rajausviiva'};

export function VarikamuEnterpriseStudioPage(){
 const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLImageElement>(null),stageRef=useRef<HTMLDivElement>(null),finalRef=useRef<HTMLCanvasElement>(null),protectCanvasRef=useRef<HTMLCanvasElement>(null),selectionCanvasRef=useRef<HTMLCanvasElement>(null),sourceRef=useRef<HTMLCanvasElement|null>(null),prepRef=useRef<HTMLCanvasElement|null>(null),manualRef=useRef<MaskLayer|null>(null),smartRef=useRef<MaskLayer|null>(null),protectRef=useRef<MaskLayer|null>(null),selectionRef=useRef<MaskLayer|null>(null),layersRef=useRef<SurfaceLayer[]>([]),drawingRef=useRef(false),lastRef=useRef<Point|null>(null),startRef=useRef<Point|null>(null),strokeRef=useRef<Point[]>([]),generationRef=useRef(0),lastClientRef=useRef<{x:number;y:number}|null>(null);
 const[imageUrl,setImageUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('brush'),[color,setColor]=useState('#9FB4C3'),[brushSize,setBrushSize]=useState(38),[coverSize,setCoverSize]=useState(22),[opacity,setOpacity]=useState(.72),[passes,setPasses]=useState<1|2|3|4>(2),[smart,setSmart]=useState(true),[advanced,setAdvanced]=useState(false),[stabilizer,setStabilizer]=useState(76),[tolerance,setTolerance]=useState(32),[rollerShape,setRollerShape]=useState<RollerShape>('normal'),[showProtection,setShowProtection]=useState(true),[showSelection,setShowSelection]=useState(true),[smartBusy,setSmartBusy]=useState(false),[history,setHistory]=useState<Snapshot[]>([]),[historyIndex,setHistoryIndex]=useState(-1),[viewMode,setViewMode]=useState<ViewMode>('after'),[compareAt,setCompareAt]=useState(50),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[showGuide,setShowGuide]=useState(true),[message,setMessage]=useState('Aloita lataamalla kuva. Maalaa sitten pieni vihje haluamallesi pinnalle ja valitse väri.'),[wallpaperKind,setWallpaperKind]=useState<WallpaperKind>('linen'),[wallpaperScale,setWallpaperScale]=useState(1),[wallpaperRotation,setWallpaperRotation]=useState(0),[wallpaperOpacity,setWallpaperOpacity]=useState(.96),[wallpaperFg,setWallpaperFg]=useState('#B6A48F'),[wallpaperBg,setWallpaperBg]=useState('#F2EBDD');
 const loadFile=(file?:File)=>{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024)return;if(imageUrl?.startsWith('blob:'))URL.revokeObjectURL(imageUrl);setImageUrl(URL.createObjectURL(file));setHistory([]);setHistoryIndex(-1);setZoom(1);setPan({x:0,y:0});layersRef.current=[];setViewMode('after')};
 const onImageLoad=()=>{const img=imageRef.current,final=finalRef.current,pc=protectCanvasRef.current,sc=selectionCanvasRef.current;if(!img||!final||!pc||!sc)return;const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),width=Math.max(1,Math.round(img.naturalWidth*scale)),height=Math.max(1,Math.round(img.naturalHeight*scale));setSize({width,height});for(const c of [final,pc,sc]){c.width=width;c.height=height}const s=document.createElement('canvas');s.width=width;s.height=height;s.getContext('2d')?.drawImage(img,0,0,width,height);sourceRef.current=s;const prep=document.createElement('canvas');prep.width=width;prep.height=height;prepRef.current=prep;manualRef.current=new MaskLayer(width,height);smartRef.current=new MaskLayer(width,height);protectRef.current=new MaskLayer(width,height);selectionRef.current=new MaskLayer(width,height);layersRef.current=[];renderCurrent();window.setTimeout(()=>commit(),0)};
 const point=(e:ReactPointerEvent<HTMLDivElement>)=>{const stage=stageRef.current;if(!stage||!size.width)return null;const r=stage.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*size.width,0,size.width-1),y:clamp((e.clientY-r.top)/r.height*size.height,0,size.height-1)}};
 const smooth=(a:Point,b:Point)=>{const s=clamp(stabilizer/100,0,.92);return{x:a.x*s+b.x*(1-s),y:a.y*s+b.y*(1-s)}};
 const snap=(a:Point,b:Point)=>{const dx=b.x-a.x,dy=b.y-a.y,d=Math.abs(Math.atan2(dy,dx)*180/Math.PI);if(d<12||d>168)return{x:b.x,y:a.y};if(Math.abs(d-90)<12)return{x:a.x,y:b.y};return b};
 const canvasMask=(draw:(ctx:CanvasRenderingContext2D)=>void)=>{const c=document.createElement('canvas');c.width=size.width;c.height=size.height;const ctx=c.getContext('2d'),m=new MaskLayer(size.width,size.height);if(!ctx)return m;ctx.strokeStyle='#fff';ctx.fillStyle='#fff';draw(ctx);const d=ctx.getImageData(0,0,c.width,c.height).data;for(let i=0;i<m.alpha.length;i++)m.alpha[i]=d[i*4+3];return m};
 const lineMask=(a:Point,b:Point,width:number,square=false,soft=false)=>canvasMask(ctx=>{ctx.lineWidth=width;ctx.lineCap=square?'square':'round';ctx.lineJoin='round';ctx.globalAlpha=soft?0.58:1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()});
 const shapeMask=(a:Point,b:Point,kind:'line'|'rect'|'circle',fill=false)=>canvasMask(ctx=>{ctx.lineWidth=brushSize;ctx.lineCap='round';ctx.lineJoin='round';if(kind==='line'){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();return}if(kind==='rect'){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);if(fill)ctx.fillRect(x,y,w,h);else ctx.strokeRect(x,y,w,h);return}const cx=(a.x+b.x)/2,cy=(a.y+b.y)/2,rx=Math.abs(b.x-a.x)/2,ry=Math.abs(b.y-a.y)/2;ctx.beginPath();ctx.ellipse(cx,cy,Math.max(1,rx),Math.max(1,ry),0,0,Math.PI*2);if(fill)ctx.fill();else ctx.stroke()});
 const selected=(raw:MaskLayer)=>{const sel=selectionRef.current;return sel&&!sel.isEmpty()?raw.intersect(sel):raw};
 const activeMask=()=>{const m=manualRef.current,s=smartRef.current;if(!m||!s)return null;return mergeManualAndSmart(m,s)};
 const workingBase=()=>{const s=sourceRef.current,p=prepRef.current;if(!s)return null;const c=document.createElement('canvas');c.width=s.width;c.height=s.height;const x=c.getContext('2d');if(!x)return null;x.drawImage(s,0,0);if(p)x.drawImage(p,0,0);return c};
 const renderLayer=(canvas:HTMLCanvasElement,layer:SurfaceLayer)=>{const mask=MaskLayer.fromRle(canvas.width,canvas.height,layer.mask);if(layer.kind==='paint'){const p=new CanvasPipeline(canvas);const base=document.createElement('canvas');base.width=canvas.width;base.height=canvas.height;base.getContext('2d')!.drawImage(canvas,0,0);p.setSize({width:canvas.width,height:canvas.height});p.renderBaseImage(base);p.applyPaintMask(mask,{tint:rgb(layer.color??'#ffffff'),coat:layer.passes??4,opacity:layer.opacity??1})}else if(layer.wallpaper)applyWallpaper(canvas,mask,layer.wallpaper)};
 const renderCurrent=()=>{const f=finalRef.current,pr=protectRef.current,b=workingBase();if(!f||!pr||!b)return;const x=f.getContext('2d');if(!x)return;f.width=b.width;f.height=b.height;x.drawImage(b,0,0);for(const layer of layersRef.current)renderLayer(f,{...layer,mask:MaskLayer.fromRle(size.width,size.height,layer.mask).subtract(pr).toRle()});const current=activeMask();if(current&&!current.isEmpty()){const p=new CanvasPipeline(f),base=document.createElement('canvas');base.width=f.width;base.height=f.height;base.getContext('2d')!.drawImage(f,0,0);p.setSize({width:f.width,height:f.height});p.renderBaseImage(base);p.applyPaintMask(current.subtract(pr),{tint:rgb(color),coat:passes,opacity})}drawOverlays()};
 const drawOverlays=()=>{const pc=protectCanvasRef.current,pr=protectRef.current,sc=selectionCanvasRef.current,sel=selectionRef.current;if(pc&&pr){const x=pc.getContext('2d')!;x.clearRect(0,0,pc.width,pc.height);const img=x.createImageData(pc.width,pc.height);for(let i=0;i<pr.alpha.length;i++){if(!pr.alpha[i])continue;const q=i*4;img.data[q]=249;img.data[q+1]=115;img.data[q+2]=22;img.data[q+3]=Math.round(pr.alpha[i]*.5)}x.putImageData(img,0,0)}if(sc&&sel){const x=sc.getContext('2d')!;x.clearRect(0,0,sc.width,sc.height);const img=x.createImageData(sc.width,sc.height);for(let i=0;i<sel.alpha.length;i++){if(!sel.alpha[i])continue;const q=i*4;img.data[q]=59;img.data[q+1]=130;img.data[q+2]=246;img.data[q+3]=42}x.putImageData(img,0,0)}};
 const freezePaint=()=>{const m=activeMask();if(!m||m.isEmpty())return;layersRef.current.push({id:crypto.randomUUID(),kind:'paint',mask:m.toRle(),color,opacity,passes});manualRef.current?.clear();smartRef.current?.clear()};
 const erasePrep=(mask:MaskLayer)=>{const p=prepRef.current;if(!p)return;const x=p.getContext('2d')!,tmp=document.createElement('canvas');tmp.width=p.width;tmp.height=p.height;tmp.getContext('2d')!.putImageData(mask.toImageData(),0,0);x.save();x.globalCompositeOperation='destination-out';x.drawImage(tmp,0,0);x.restore()};
 const applyPrep=(raw:MaskLayer,mode:'scraper'|'putty'|'sand')=>{const s=sourceRef.current,p=prepRef.current,pr=protectRef.current;if(!s||!p||!pr)return;const mask=selected(raw).subtract(pr),px=p.getContext('2d')!;const selection=document.createElement('canvas');selection.width=s.width;selection.height=s.height;selection.getContext('2d')!.putImageData(mask.toImageData(),0,0);const effect=document.createElement('canvas');effect.width=s.width;effect.height=s.height;const ex=effect.getContext('2d')!;ex.save();ex.filter=mode==='scraper'?'blur(1.15px) contrast(90%) saturate(82%)':mode==='putty'?'blur(3.4px) contrast(88%) saturate(62%) brightness(1.12)':'blur(2px) contrast(92%) saturate(90%)';ex.drawImage(s,0,0);ex.restore();if(mode==='putty'){ex.globalCompositeOperation='source-atop';ex.fillStyle='rgba(228,220,207,.48)';ex.fillRect(0,0,effect.width,effect.height)}ex.globalCompositeOperation='destination-in';ex.drawImage(selection,0,0);px.drawImage(effect,0,0);renderCurrent()};
 const subtractFromLayers=(mask:MaskLayer)=>{layersRef.current=layersRef.current.map(l=>({...l,mask:MaskLayer.fromRle(size.width,size.height,l.mask).subtract(mask).toRle()}))};
 const applyManual=(a:Point,b:Point)=>{const m=manualRef.current,sm=smartRef.current,pr=protectRef.current;if(!m||!sm||!pr)return;let width=brushSize,square=false,soft=false;if(tool==='roller'){width=brushSize*(rollerShape==='wide'?3.1:rollerShape==='edge'?1.15:2.1);square=true}else if(tool==='corner'){width=Math.max(4,brushSize*.52);square=true}else if(tool==='spray'){width=brushSize*1.7;soft=true}const mask=selected(lineMask(a,b,width,square,soft));if(tool==='eraser'){manualRef.current=m.subtract(mask);smartRef.current=sm.subtract(mask);subtractFromLayers(mask);renderCurrent();return}if(tool==='prepEraser'){erasePrep(mask);renderCurrent();return}if(tool==='scraper'||tool==='putty'||tool==='sand'){applyPrep(mask,tool);return}manualRef.current=m.union(mask.subtract(pr));renderCurrent()};
 const applyCover=(a:Point,b:Point,erase=false)=>{const pr=protectRef.current,m=manualRef.current,sm=smartRef.current;if(!pr||!m||!sm)return;const mask=selected(lineMask(a,b,coverSize));if(erase){protectRef.current=pr.subtract(mask);renderCurrent();return}protectRef.current=pr.union(mask);manualRef.current=m.subtract(mask);smartRef.current=sm.subtract(mask);subtractFromLayers(mask);erasePrep(mask);renderCurrent()};
 const applyShape=(a:Point,b:Point,kind:'line'|'rect'|'circle')=>{const m=manualRef.current,pr=protectRef.current;if(!m||!pr)return;manualRef.current=m.union(selected(shapeMask(a,b,kind,false)).subtract(pr));renderCurrent()};
 const applySelectionShape=(a:Point,b:Point,kind:'rect'|'circle')=>{selectionRef.current=shapeMask(a,b,kind,true);setShowSelection(true);renderCurrent();setMessage('Valinta valmis. Nyt sama alue voidaan maalata, tapetoida, kitata, hioa tai suojata.')};
 const applyWallpaperToSelection=()=>{freezePaint();const pr=protectRef.current,sel=selectionRef.current,active=activeMask();if(!pr)return;let target=sel&&!sel.isEmpty()?sel:active;if(!target||target.isEmpty()){setMessage('Valitse ensin alue Valinta-työkaluilla tai maalaa alue, johon tapetti lisätään.');return}target=target.subtract(pr);layersRef.current.push({id:crypto.randomUUID(),kind:'wallpaper',mask:target.toRle(),wallpaper:{kind:wallpaperKind,scale:wallpaperScale,rotation:wallpaperRotation,opacity:wallpaperOpacity,foreground:wallpaperFg,background:wallpaperBg,offsetX:0,offsetY:0}});renderCurrent();commit();setMessage('Tapetti lisättiin vain valitulle alueelle.')};
 const smartFill=async(seed:Point)=>{const s=sourceRef.current,m=manualRef.current,old=smartRef.current,pr=protectRef.current;if(!s||!m||!old||!pr)return;const image=s.getContext('2d')!.getImageData(0,0,s.width,s.height),gen=++generationRef.current;setSmartBusy(true);try{const result=await segmentation.segment({imageId:`${s.width}x${s.height}:${imageUrl??'local'}`,image,point:seed,tolerance});if(gen!==generationRef.current)return;const safe=selected(result.mask).subtract(pr);if(safe.coverage()>.32){smartRef.current=old;setMessage('Smart hylättiin turvallisuuden vuoksi. Oma siveltimen jälki säilyi.');return}smartRef.current=mergeManualAndSmart(m,safe).subtract(m);renderCurrent();setMessage(result.source==='remote-sam'?'Smart tunnisti pinnan.':'Paikallinen Smart täydensi vain turvallisen alueen.')}catch{setMessage('Smart ei ollut käytettävissä. Oma työ säilyi.')}finally{if(gen===generationRef.current)setSmartBusy(false)}};
 const down=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!imageUrl||viewMode!=='after')return;e.preventDefault();if(tool==='pan'){drawingRef.current=true;lastClientRef.current={x:e.clientX,y:e.clientY};return}const p=point(e);if(!p)return;e.currentTarget.setPointerCapture?.(e.pointerId);drawingRef.current=true;lastRef.current=p;startRef.current=p;strokeRef.current=[p]};
 const move=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawingRef.current)return;e.preventDefault();if(tool==='pan'&&lastClientRef.current){const dx=e.clientX-lastClientRef.current.x,dy=e.clientY-lastClientRef.current.y;lastClientRef.current={x:e.clientX,y:e.clientY};setPan(v=>({x:v.x+dx,y:v.y+dy}));return}if(!lastRef.current)return;const raw=point(e);if(!raw)return;const p=smooth(lastRef.current,raw);strokeRef.current.push(p);if(tool==='selectBrush'){const current=selectionRef.current;if(current)selectionRef.current=current.union(lineMask(lastRef.current,p,brushSize));renderCurrent()}else if(!['cover','coverEraser','line','rect','circle','selectRect','selectCircle','boundary'].includes(tool))applyManual(lastRef.current,p);lastRef.current=p};
 const up=(e?:ReactPointerEvent<HTMLDivElement>)=>{e?.preventDefault();if(!drawingRef.current)return;drawingRef.current=false;if(tool==='pan'){lastClientRef.current=null;return}const start=startRef.current,last=lastRef.current,pts=strokeRef.current;lastRef.current=null;startRef.current=null;if(start&&last&&(tool==='cover'||tool==='coverEraser')){applyCover(start,snap(start,last),tool==='coverEraser');commit();return}if(start&&last&&tool==='boundary'){applyCover(start,snap(start,last),false);commit();setMessage('Rajausviiva lisättiin. Se toimii yhteisenä rajana maalille, tapetille ja valmistelulle.');return}if(start&&last&&(tool==='line'||tool==='rect'||tool==='circle')){applyShape(start,last,tool);commit();return}if(start&&last&&(tool==='selectRect'||tool==='selectCircle')){applySelectionShape(start,last,tool==='selectRect'?'rect':'circle');commit();return}commit();if(smart&&(tool==='brush'||tool==='spray'||tool==='corner'||tool==='roller')&&pts.length)void smartFill(pts[Math.floor(pts.length/2)])};
 const snapshot=():Snapshot|null=>{const m=manualRef.current,s=smartRef.current,p=protectRef.current,sel=selectionRef.current,prep=prepRef.current;if(!m||!s||!p||!sel||!prep)return null;return{manual:m.toRle(),smart:s.toRle(),protect:p.toRle(),selection:sel.toRle(),prep:prep.toDataURL('image/png'),layers:JSON.parse(JSON.stringify(layersRef.current)) as SurfaceLayer[]}};
 const commit=()=>{const snap=snapshot();if(!snap)return;const next=[...history.slice(0,historyIndex+1),snap].slice(-30);setHistory(next);setHistoryIndex(next.length-1)};
 const restore=(i:number)=>{const snap=history[i],prep=prepRef.current;if(!snap||!prep)return;manualRef.current=MaskLayer.fromRle(size.width,size.height,snap.manual);smartRef.current=MaskLayer.fromRle(size.width,size.height,snap.smart);protectRef.current=MaskLayer.fromRle(size.width,size.height,snap.protect);selectionRef.current=MaskLayer.fromRle(size.width,size.height,snap.selection);layersRef.current=JSON.parse(JSON.stringify(snap.layers)) as SurfaceLayer[];const img=new Image();img.onload=()=>{prep.getContext('2d')!.clearRect(0,0,prep.width,prep.height);prep.getContext('2d')!.drawImage(img,0,0);setHistoryIndex(i);renderCurrent()};img.src=snap.prep};
 const reset=()=>{manualRef.current?.clear();smartRef.current?.clear();selectionRef.current?.clear();layersRef.current=[];prepRef.current?.getContext('2d')?.clearRect(0,0,size.width,size.height);renderCurrent();commit()};
 const clearSelection=()=>{selectionRef.current?.clear();renderCurrent();setMessage('Valinta poistettiin. Työkalut vaikuttavat jälleen koko kuvaan.')};
 const clearProtection=()=>{protectRef.current?.clear();renderCurrent();commit()};
 const chooseColor=(next:string)=>{if(next===color)return;freezePaint();setColor(next);window.setTimeout(renderCurrent,0);setMessage('Uusi väri aloittaa uuden maalikerroksen. Aiempi väri säilyy omalla alueellaan.')};
 const download=(type:'png'|'jpg')=>{const c=finalRef.current;if(!c)return;const a=document.createElement('a');a.download=`varikamu-${Date.now()}.${type}`;a.href=type==='jpg'?c.toDataURL('image/jpeg',.94):c.toDataURL('image/png');a.click()};
 const ratio=size.width&&size.height?size.width/size.height:4/3,stageWidth=size.width?`min(100%, calc(58dvh * ${ratio}))`:'100%',finalStyle=useMemo(()=>viewMode==='before'?{display:'none'}:viewMode==='compare'?{clipPath:`inset(0 ${100-compareAt}% 0 0)`}:undefined,[viewMode,compareAt]);
 const cursor=tool==='pan'?'grab':tool.includes('select')?'cell':tool==='eraser'||tool==='prepEraser'||tool==='coverEraser'?'not-allowed':tool==='roller'?'ns-resize':'crosshair';
 const toolBtn=(t:Tool,label?:string)=><button className={tool===t?'btn-primary':'btn-outline'} onClick={()=>{setTool(t);if(t==='cover'||t==='coverEraser'||t==='boundary')setShowProtection(true);if(t.includes('select'))setShowSelection(true)}}>{label??toolLabel[t]}</button>;
 return <section className="min-h-screen w-full overflow-x-hidden bg-navy-50 px-2 py-3 pb-24 lg:pb-3"><div className="container-base w-full max-w-6xl">
  <div className="mb-3 flex items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase text-orange-600">VäriKamu-maalaussuunnittelija</p><h1 className="font-display text-xl font-extrabold text-navy-950 sm:text-2xl">Kokeile värejä omassa kuvassasi</h1></div><button className="btn-outline" onClick={()=>setShowGuide(v=>!v)}><HelpCircle className="size-4"/>Ohje</button></div>
  {showGuide&&<div className="mb-4 rounded-2xl border border-orange-200 bg-orange-50 p-4 text-sm"><strong>1. Lisää kuva → 2. Merkitse pinta → 3. Valitse väri → 4. Vertaa → 5. Pyydä tarjous</strong><p className="mt-1 text-xs">Smart-tila auttaa tunnistamaan maalattavaa pintaa. Esikatselu on suuntaa antava; lopullinen sävy riippuu pinnasta ja valaistuksesta.</p></div>}
  <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_380px]"><div className="card min-w-0 overflow-hidden p-2 sm:p-4">
   {!imageUrl?<div className="grid min-h-[46vh] place-items-center rounded-2xl border-2 border-dashed border-navy-200 bg-white p-5 text-center"><div><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-4 text-xl font-bold">Ota kuva tai lataa kuva</h2><div className="mt-5 flex justify-center gap-3"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/>Ota kuva</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Lataa kuva</button></div></div></div>:<><div className="mb-2 flex items-center justify-between rounded-xl bg-navy-900 px-3 py-2 text-xs font-bold text-white"><span>Työkalu: {toolLabel[tool]}</span><span>{Math.round(zoom*100)}%</span></div><div className="w-full overflow-hidden rounded-2xl bg-navy-950 p-1"><div className="flex min-h-[260px] items-center justify-center overflow-hidden"><div ref={stageRef} className="relative shrink-0 overflow-hidden rounded-xl bg-black" style={{width:stageWidth,aspectRatio:`${size.width}/${size.height}`,maxWidth:'100%',transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`,touchAction:'none',cursor}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><img ref={imageRef} src={imageUrl} onLoad={onImageLoad} draggable={false} className="pointer-events-none absolute inset-0 h-full w-full object-fill"/><canvas ref={finalRef} className="pointer-events-none absolute inset-0 h-full w-full" style={finalStyle}/><canvas ref={protectCanvasRef} className={`pointer-events-none absolute inset-0 h-full w-full ${showProtection?'opacity-100':'opacity-0'}`}/><canvas ref={selectionCanvasRef} className={`pointer-events-none absolute inset-0 h-full w-full ${showSelection?'opacity-100':'opacity-0'}`}/></div></div></div><div className="mt-2 hidden flex-wrap gap-2 lg:flex"><button className="btn-outline" onClick={()=>setZoom(z=>Math.max(.6,z-.2))}><ZoomOut className="size-4"/>−</button><button className="btn-outline" onClick={()=>{setZoom(1);setPan({x:0,y:0})}}><Maximize2 className="size-4"/>Sovita</button><button className="btn-outline" onClick={()=>setZoom(z=>Math.min(4,z+.2))}><ZoomIn className="size-4"/>+</button>{toolBtn('pan','✋ Siirrä')}</div><div className="mt-3 grid grid-cols-3 gap-2"><button className={viewMode==='before'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('before')}>Ennen</button><button className={viewMode==='after'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('after')}>Jälkeen</button><button className={viewMode==='compare'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('compare')}>Vertaa</button></div>{viewMode==='compare'&&<input className="mt-3 w-full" type="range" min="5" max="95" value={compareAt} onChange={e=>setCompareAt(Number(e.target.value))}/>}</>}
   <input ref={fileRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>loadFile(e.target.files?.[0])}/><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>loadFile(e.target.files?.[0])}/>
   {imageUrl&&<div className="mt-2 hidden flex-wrap gap-2 lg:flex"><button className="btn-outline" onClick={()=>historyIndex>0&&restore(historyIndex-1)} disabled={historyIndex<=0}><Undo2 className="size-4"/>Kumoa</button><button className="btn-outline" onClick={()=>historyIndex<history.length-1&&restore(historyIndex+1)} disabled={historyIndex>=history.length-1}><Redo2 className="size-4"/>Tee uudelleen</button><button className="btn-outline" onClick={reset}><RotateCcw className="size-4"/>Tyhjennä työ</button><button className="btn-outline" onClick={()=>setShowProtection(v=>!v)}>{showProtection?'Piilota suoja':'Näytä suoja'}</button><button className="btn-outline" onClick={()=>setShowSelection(v=>!v)}>{showSelection?'Piilota valinta':'Näytä valinta'}</button></div>}
  </div><aside className="hidden space-y-3 lg:block">
   <details open className="card p-4"><summary className="cursor-pointer font-bold">🎨 Maalaus</summary><div className="mt-3 grid grid-cols-2 gap-2">{toolBtn('brush','🖌 Sivellin')}{toolBtn('spray','💨 Maalisuihke')}{toolBtn('corner','◩ Kulmasivellin')}{toolBtn('roller','▰ Tela')}</div>{tool==='roller'&&<div className="mt-3 grid grid-cols-3 gap-2">{(['normal','wide','edge'] as RollerShape[]).map(r=><button key={r} className={rollerShape===r?'btn-primary':'btn-outline'} onClick={()=>setRollerShape(r)}>{r==='normal'?'Normaali':r==='wide'?'Leveä':'Reuna'}</button>)}</div>}<button className="mt-3 w-full rounded-xl border border-orange-300 bg-orange-50 p-3 text-left" onClick={()=>setSmart(v=>!v)}><strong><Sparkles className="mr-1 inline size-4"/>Älykäs maalaustila {smart?'käytössä':'pois'} {smartBusy?'· tunnistaa…':''}</strong><span className="mt-1 block text-xs text-navy-600">Auttaa tunnistamaan pinnan oman siveltimenvedon perusteella.</span></button></details>
   <button type="button" className="btn-outline w-full" onClick={()=>setAdvanced(v=>!v)}>{advanced?'Piilota lisätyökalut':'Näytä lisätyökalut'}</button>
   {advanced&&<details className="card p-4"><summary className="cursor-pointer font-bold">🎯 Valinta ja rajaus</summary><div className="mt-3 grid grid-cols-2 gap-2">{toolBtn('selectBrush','✎ Valintakynä')}{toolBtn('selectRect','▣ Suorakulmio')}{toolBtn('selectCircle','◉ Ympyrä')}{toolBtn('boundary','┃ Rajausviiva')}</div><div className="mt-2 flex gap-2"><button className="btn-outline flex-1" onClick={clearSelection}>Poista valinta</button><button className="btn-outline flex-1" onClick={clearProtection}>Poista rajat</button></div><p className="mt-2 text-xs text-navy-600">Sininen alue = yhteinen valinta kaikille työkaluille. Rajausviiva estää maalin, tapetin, kitin ja hionnan ylityksen.</p></details>}
   {advanced&&<details className="card p-4"><summary className="cursor-pointer font-bold">🛡️ Suojaus ja pyyhkimet</summary><div className="mt-3 grid grid-cols-2 gap-2">{toolBtn('cover','🛡 Suojaa')}{toolBtn('coverEraser','− Poista suojaus')}{toolBtn('eraser','⌫ Poista maali')}{toolBtn('prepEraser','⌫ Poista valmistelu')}</div><div className="mt-3 grid grid-cols-4 gap-2">{covers.map(c=><button key={c.label} className={`rounded-xl border p-2 text-xs font-bold ${coverSize===c.px?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>setCoverSize(c.px)}>{c.label}</button>)}</div></details>}
   {advanced&&<details className="card p-4"><summary className="cursor-pointer font-bold">🧰 Valmistelu</summary><div className="mt-3 grid grid-cols-2 gap-2">{toolBtn('scraper','🪚 Kaavin')}{toolBtn('putty','🧱 Kitti')}{toolBtn('sand','🧽 Hionta')}{toolBtn('prepEraser','⌫ Poista valmistelu')}</div></details>}
   {advanced&&<details className="card p-4"><summary className="cursor-pointer font-bold">📐 Geometria</summary><div className="mt-3 grid grid-cols-3 gap-2">{toolBtn('line','／ Suora')}{toolBtn('rect','▭ Suorakulmio')}{toolBtn('circle','◯ Ympyrä')}</div><p className="mt-2 text-xs text-navy-600">Vedä hiirellä tai sormella: pieni veto = pieni muoto, suuri veto = suuri muoto.</p></details>}
   <details open className="card p-4"><summary className="cursor-pointer font-bold">📏 Koko</summary><div className="mt-3 grid grid-cols-4 gap-2">{brushes.map(b=><button key={b.label} className={`rounded-xl border p-2 text-xs font-bold ${brushSize===b.px?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>setBrushSize(b.px)}>{b.label}</button>)}</div></details>
   <details open className="card p-4"><summary className="cursor-pointer font-bold">🎨 Väri ja peittävyys</summary><div className="mt-3 flex flex-wrap gap-2">{palette.map(c=><button key={c} aria-label={c} onClick={()=>chooseColor(c)} className={`h-9 w-9 rounded-full border-2 ${color===c?'border-orange-500 ring-2 ring-orange-200':'border-white'}`} style={{backgroundColor:c}}/>)}<input title="Mukautettu väri" type="color" value={color} onChange={e=>chooseColor(e.target.value)} className="h-9 w-12"/></div><label className="mt-4 block text-sm font-bold">Peittävyys {Math.round(opacity*100)} %<input className="mt-2 w-full accent-orange-500" type="range" min="0" max="100" step="1" value={Math.round(opacity*100)} onChange={e=>{setOpacity(Number(e.target.value)/100);window.setTimeout(renderCurrent,0)}}/></label><div className="mt-2 grid grid-cols-5 gap-1">{[0,25,50,75,100].map(v=><button key={v} className="rounded-lg border px-1 py-2 text-xs font-bold" onClick={()=>{setOpacity(v/100);window.setTimeout(renderCurrent,0)}}>{v}%</button>)}</div><div className="mt-4 grid grid-cols-4 gap-2">{([1,2,3,4] as const).map(n=><button key={n} className={`rounded-xl border p-2 text-xs font-bold ${passes===n?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>{setPasses(n);window.setTimeout(renderCurrent,0)}}>{n}×</button>)}</div></details>
   {advanced&&<details className="card p-4"><summary className="cursor-pointer font-bold">🧾 Tapetti</summary><div className="mt-3 grid grid-cols-2 gap-2">{wallpaperKinds.map(k=><button key={k} className={wallpaperKind===k?'btn-primary':'btn-outline'} onClick={()=>setWallpaperKind(k)}>{wallpaperLabels[k]}</button>)}</div><label className="mt-3 block text-sm font-bold">Kuvion koko {Math.round(wallpaperScale*100)}%<input className="mt-2 w-full" type="range" min="35" max="250" value={Math.round(wallpaperScale*100)} onChange={e=>setWallpaperScale(Number(e.target.value)/100)}/></label><label className="mt-3 block text-sm font-bold">Kierto {wallpaperRotation}°<input className="mt-2 w-full" type="range" min="-180" max="180" value={wallpaperRotation} onChange={e=>setWallpaperRotation(Number(e.target.value))}/></label><label className="mt-3 block text-sm font-bold">Peittävyys {Math.round(wallpaperOpacity*100)}%<input className="mt-2 w-full" type="range" min="20" max="100" value={Math.round(wallpaperOpacity*100)} onChange={e=>setWallpaperOpacity(Number(e.target.value)/100)}/></label><div className="mt-3 flex gap-2"><input type="color" value={wallpaperFg} onChange={e=>setWallpaperFg(e.target.value)} className="h-10 w-16"/><input type="color" value={wallpaperBg} onChange={e=>setWallpaperBg(e.target.value)} className="h-10 w-16"/><button className="btn-primary flex-1" onClick={applyWallpaperToSelection}>Lisää tapetti valintaan</button></div></details>}
   {advanced&&<details className="card p-4"><summary className="cursor-pointer font-bold">⚙️ Tarkkuus</summary><label className="mt-3 block text-sm font-bold">Käden vakautus {stabilizer}%<input className="mt-2 w-full" type="range" min="0" max="90" value={stabilizer} onChange={e=>setStabilizer(Number(e.target.value))}/></label><label className="mt-3 block text-sm font-bold">Smart-herkkyys {tolerance}<input className="mt-2 w-full" type="range" min="18" max="64" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></label></details>}
   <div className="card p-4"><p className="text-sm text-navy-700">{message}</p><div className="mt-3 grid grid-cols-2 gap-2"><button className="btn-outline" onClick={()=>download('png')} disabled={!imageUrl}><Download className="size-4"/>Tallenna PNG</button><button className="btn-outline" onClick={()=>download('jpg')} disabled={!imageUrl}><Download className="size-4"/>Tallenna JPG</button></div><a className={`btn-primary mt-3 w-full ${!imageUrl?'pointer-events-none opacity-50':''}`} href="/yhteystiedot?source=varikamu" onClick={()=>download('jpg')}>Tallenna suunnitelma ja pyydä tarjous</a><p className="mt-2 text-xs text-navy-600">Suunnitelma tallennetaan JPG-kuvana ennen tarjouslomaketta. Saat henkilökohtaisen tarjouksen yleensä 24 tunnin kuluessa. Esikatselu on suuntaa antava.</p></div>
  </aside></div>
 </div>
 {imageUrl&&<VarikamuMobileToolbar tool={tool} setTool={setTool} brushSize={brushSize} setBrushSize={setBrushSize} coverSize={coverSize} setCoverSize={setCoverSize} color={color} palette={palette} chooseColor={chooseColor} opacity={opacity} onOpacityChange={value=>{setOpacity(value);window.setTimeout(renderCurrent,0)}} passes={passes} onPassesChange={value=>{setPasses(value);window.setTimeout(renderCurrent,0)}} smart={smart} smartBusy={smartBusy} toggleSmart={()=>setSmart(v=>!v)} rollerShape={rollerShape} setRollerShape={setRollerShape} wallpaperKind={wallpaperKind} wallpaperKinds={wallpaperKinds} wallpaperLabels={wallpaperLabels} setWallpaperKind={setWallpaperKind} wallpaperScale={wallpaperScale} setWallpaperScale={setWallpaperScale} wallpaperRotation={wallpaperRotation} setWallpaperRotation={setWallpaperRotation} wallpaperOpacity={wallpaperOpacity} setWallpaperOpacity={setWallpaperOpacity} wallpaperFg={wallpaperFg} wallpaperBg={wallpaperBg} setWallpaperFg={setWallpaperFg} setWallpaperBg={setWallpaperBg} applyWallpaper={applyWallpaperToSelection} clearSelection={clearSelection} clearProtection={clearProtection} toggleProtection={()=>setShowProtection(v=>!v)} toggleSelection={()=>setShowSelection(v=>!v)} showProtection={showProtection} showSelection={showSelection} undo={()=>historyIndex>0&&restore(historyIndex-1)} redo={()=>historyIndex<history.length-1&&restore(historyIndex+1)} canUndo={historyIndex>0} canRedo={historyIndex<history.length-1} reset={reset} download={()=>download('jpg')} zoomOut={()=>setZoom(z=>Math.max(.6,z-.2))} zoomIn={()=>setZoom(z=>Math.min(4,z+.2))} fit={()=>{setZoom(1);setPan({x:0,y:0})}}/>}
 </section>
}
