import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Camera, Download, Eraser, Eye, EyeOff, HelpCircle, Maximize2, Paintbrush, PaintRoller, Redo2, RotateCcw, Shield, Sparkles, Undo2, Upload, ZoomIn, ZoomOut } from 'lucide-react';

type Tool='brush'|'roller'|'eraser'|'cover';
type Point={x:number;y:number};
type ViewMode='before'|'after'|'compare';
type BrushPreset={id:string;label:string;detail:string;px:number};

const palette=['#F2EFE6','#D8C9B5','#C9CBC8','#A7B19B','#9FB4C3','#B86F52','#496255','#45494B','#1D2022','#FF6B9D','#6C5CE7','#00B894'];
const brushes:BrushPreset[]=[
 {id:'2',label:'2 cm',detail:'Tarkka',px:18},{id:'3',label:'3 cm',detail:'Reunat',px:26},{id:'5',label:'5 cm',detail:'Yleinen',px:38},{id:'7',label:'7 cm',detail:'Leveä',px:54},{id:'10',label:'10 cm',detail:'Julkisivu',px:72},
];
const covers=[{label:'1 cm',px:12},{label:'2 cm',px:22},{label:'5 cm',px:42},{label:'10 cm',px:76}];
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const rgb=(hex:string)=>{const n=parseInt(hex.slice(1),16);return {r:(n>>16)&255,g:(n>>8)&255,b:n&255};};

export function VarikamuPaintStudioPage(){
 const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLImageElement>(null),stageRef=useRef<HTMLDivElement>(null);
 const paintRef=useRef<HTMLCanvasElement>(null),protectRef=useRef<HTMLCanvasElement>(null),sourceRef=useRef<HTMLCanvasElement|null>(null);
 const drawingRef=useRef(false),lastRef=useRef<Point|null>(null),startRef=useRef<Point|null>(null),strokePointsRef=useRef<Point[]>([]);
 const [imageUrl,setImageUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('brush');
 const [color,setColor]=useState('#D99518'),[brushSize,setBrushSize]=useState(38),[coverSize,setCoverSize]=useState(22),[opacity,setOpacity]=useState(.42),[passes,setPasses]=useState(2);
 const [smartAssist,setSmartAssist]=useState(true),[stabilizer,setStabilizer]=useState(72),[tolerance,setTolerance]=useState(58),[edgeLock,setEdgeLock]=useState(68);
 const [showProtection,setShowProtection]=useState(true),[history,setHistory]=useState<string[]>([]),[historyIndex,setHistoryIndex]=useState(-1);
 const [viewMode,setViewMode]=useState<ViewMode>('after'),[compareAt,setCompareAt]=useState(50),[zoom,setZoom]=useState(1),[showGuide,setShowGuide]=useState(true);
 const [message,setMessage]=useState('Smart-tila on päällä: maalaa lyhyt vihje seinälle. VäriKamu yrittää täydentää pinnan automaattisesti.');

 const loadFile=(file?:File)=>{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024)return;if(imageUrl?.startsWith('blob:'))URL.revokeObjectURL(imageUrl);setImageUrl(URL.createObjectURL(file));setHistory([]);setHistoryIndex(-1);setZoom(1);setViewMode('after');setMessage('Kuva valmis. Suojaa ensin ikkunat, ovet ja muut kohdat, joita et halua maalata.');};
 const onImageLoad=()=>{const img=imageRef.current,p=paintRef.current,k=protectRef.current;if(!img||!p||!k)return;const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));setSize({width:w,height:h});p.width=w;p.height=h;k.width=w;k.height=h;p.getContext('2d')?.clearRect(0,0,w,h);k.getContext('2d')?.clearRect(0,0,w,h);const s=document.createElement('canvas');s.width=w;s.height=h;s.getContext('2d')?.drawImage(img,0,0,w,h);sourceRef.current=s;const first=p.toDataURL('image/png');setHistory([first]);setHistoryIndex(0);};
 const point=(e:ReactPointerEvent<HTMLDivElement>):Point|null=>{const stage=stageRef.current;if(!stage||!size.width)return null;const r=stage.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*size.width,0,size.width-1),y:clamp((e.clientY-r.top)/r.height*size.height,0,size.height-1)};};
 const commit=()=>{const c=paintRef.current;if(!c)return;const next=[...history.slice(0,historyIndex+1),c.toDataURL('image/png')].slice(-35);setHistory(next);setHistoryIndex(next.length-1);};
 const protectedData=()=>protectRef.current?.getContext('2d')?.getImageData(0,0,size.width,size.height).data??null;
 const clearProtection=()=>{const c=protectRef.current;if(!c)return;c.getContext('2d')?.clearRect(0,0,c.width,c.height);setMessage('Suojaukset poistettiin. Maalaukset säilyivät.');};
 const snap=(a:Point,b:Point)=>{const dx=b.x-a.x,dy=b.y-a.y,angle=Math.atan2(dy,dx),deg=Math.abs(angle*180/Math.PI);if(deg<12||deg>168)return{x:b.x,y:a.y};if(Math.abs(deg-90)<12)return{x:a.x,y:b.y};return b;};
 const smooth=(prev:Point,next:Point)=>{const strength=clamp(stabilizer/100,0,0.92);return{x:prev.x*strength+next.x*(1-strength),y:prev.y*strength+next.y*(1-strength)};};

 const renderMask=(mask:Uint8Array,alpha=opacity,doCommit=true)=>{const source=sourceRef.current,target=paintRef.current,sctx=source?.getContext('2d'),tctx=target?.getContext('2d');if(!source||!target||!sctx||!tctx)return;const w=source.width,h=source.height,src=sctx.getImageData(0,0,w,h).data,prot=protectedData(),out=document.createElement('canvas');out.width=w;out.height=h;const octx=out.getContext('2d');if(!octx)return;const data=octx.createImageData(w,h),c=rgb(color);for(let i=0;i<mask.length;i++){if(!mask[i]||(prot&&prot[i*4+3]>0))continue;const p=i*4,lum=(src[p]*.299+src[p+1]*.587+src[p+2]*.114)/255,contrast=.52+lum*.68;data.data[p]=clamp(Math.round(c.r*contrast),0,255);data.data[p+1]=clamp(Math.round(c.g*contrast),0,255);data.data[p+2]=clamp(Math.round(c.b*contrast),0,255);data.data[p+3]=Math.round(255*alpha);}octx.putImageData(data,0,0);tctx.save();tctx.globalCompositeOperation='source-over';tctx.drawImage(out,0,0);tctx.restore();if(doCommit)commit();};
 const lineMask=(from:Point,to:Point,width:number)=>{const c=document.createElement('canvas');c.width=size.width;c.height=size.height;const ctx=c.getContext('2d');if(!ctx)return new Uint8Array(size.width*size.height);ctx.strokeStyle='#fff';ctx.lineWidth=width;ctx.lineCap=tool==='roller'?'square':'round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();const d=ctx.getImageData(0,0,c.width,c.height).data,m=new Uint8Array(c.width*c.height);for(let i=0;i<m.length;i++)if(d[i*4+3]>0)m[i]=1;return m;};
 const paintLine=(from:Point,to:Point)=>{if(tool==='eraser'){const ctx=paintRef.current?.getContext('2d');if(!ctx)return;ctx.save();ctx.globalCompositeOperation='destination-out';ctx.lineWidth=brushSize;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.restore();return;}const mask=lineMask(from,to,tool==='roller'?brushSize*2.1:brushSize);renderMask(mask,Math.min(.5,opacity/Math.max(1,passes)*1.45),false);};
 const drawCover=(a:Point,b:Point)=>{const ctx=protectRef.current?.getContext('2d');if(!ctx)return;ctx.save();ctx.globalCompositeOperation='source-over';ctx.globalAlpha=.62;ctx.strokeStyle='#F97316';ctx.lineWidth=coverSize;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore();};

 const smartFillAt=(seed:Point)=>{const source=sourceRef.current,sctx=source?.getContext('2d');if(!source||!sctx)return false;const w=source.width,h=source.height,img=sctx.getImageData(0,0,w,h),d=img.data,total=w*h,prot=protectedData(),sx=Math.floor(seed.x),sy=Math.floor(seed.y),start=sy*w+sx;if(prot&&prot[start*4+3]>0){setMessage('Tämä kohta on suojattu. Maalaa seinän sisäpuolelta.');return false;}const refs:{r:number;g:number;b:number}[]=[];const rad=Math.max(4,Math.round(Math.min(w,h)*.012));for(let oy=-rad;oy<=rad;oy+=Math.max(2,Math.round(rad/3)))for(let ox=-rad;ox<=rad;ox+=Math.max(2,Math.round(rad/3))){const x=clamp(sx+ox,0,w-1),y=clamp(sy+oy,0,h-1),p=(y*w+x)*4;refs.push({r:d[p],g:d[p+1],b:d[p+2]});}const refDist=(i:number)=>{const p=i*4;let best=999;for(const r of refs){const dr=d[p]-r.r,dg=d[p+1]-r.g,db=d[p+2]-r.b;best=Math.min(best,Math.sqrt(dr*dr+dg*dg+db*db));}return best;},local=(a:number,b:number)=>{const x=a*4,y=b*4,dr=d[x]-d[y],dg=d[x+1]-d[y+1],db=d[x+2]-d[y+2];return Math.sqrt(dr*dr+dg*dg+db*db);},lum=(i:number)=>{const p=i*4;return d[p]*.299+d[p+1]*.587+d[p+2]*.114;};const mask=new Uint8Array(total),seen=new Uint8Array(total),q=new Int32Array(total);let head=0,tail=0,count=0;seen[start]=1;q[tail++]=start;const edgeThreshold=clamp(92-edgeLock*.65,28,64),direct=tolerance*1.7,localLimit=22+tolerance*.38,far=tolerance*2.7,safety=Math.floor(total*.52);while(head<tail&&count<safety){const i=q[head++];mask[i]=1;count++;const x=i%w,y=Math.floor(i/w);const visit=(n:number)=>{if(seen[n])return;seen[n]=1;if(prot&&prot[n*4+3]>0)return;const edge=Math.max(Math.abs(lum(i)-lum(n)),local(i,n)*.5);if(edge>edgeThreshold)return;const rd=refDist(n),ld=local(i,n);if(rd<=direct||(ld<=localLimit&&rd<=far))q[tail++]=n;};if(x>0)visit(i-1);if(x<w-1)visit(i+1);if(y>0)visit(i-w);if(y<h-1)visit(i+w);}const minimum=Math.max(800,Math.round(total*.006));if(count<minimum||count>=safety){setMessage('Smart-täyttö ei ollut riittävän varma. Siveltimen oma maalaus säilyi — lisää suojaus reunalle tai maalaa hieman pidempi vihje.');return false;}for(let pass=0;pass<passes;pass++)renderMask(mask,Math.min(.36,opacity/Math.max(1,passes)),false);commit();setMessage(`Smart-maalaus täydensi pinnan ${passes} ohuella kerroksella. Alkuperäinen valo ja seinän rakenne säilytettiin.`);return true;};

 const pointerDown=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!imageUrl||viewMode!=='after')return;e.preventDefault();e.stopPropagation();const p=point(e);if(!p)return;e.currentTarget.setPointerCapture?.(e.pointerId);drawingRef.current=true;lastRef.current=p;startRef.current=p;strokePointsRef.current=[p];};
 const pointerMove=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawingRef.current||!lastRef.current)return;e.preventDefault();e.stopPropagation();const raw=point(e);if(!raw)return;const p=smooth(lastRef.current,raw);strokePointsRef.current.push(p);if(tool!=='cover')paintLine(lastRef.current,p);lastRef.current=p;};
 const pointerUp=(e?:ReactPointerEvent<HTMLDivElement>)=>{e?.preventDefault();e?.stopPropagation();if(!drawingRef.current)return;drawingRef.current=false;const start=startRef.current,last=lastRef.current,pts=strokePointsRef.current;lastRef.current=null;startRef.current=null;if(tool==='cover'&&start&&last){drawCover(start,snap(start,last));setMessage('Suora suojareuna lisättiin. Suoja voidaan piilottaa tai poistaa työn lopuksi.');return;}commit();if(smartAssist&&(tool==='brush'||tool==='roller')&&pts.length){const seed=pts[Math.floor(pts.length/2)];smartFillAt(seed);}else setMessage('Manuaalinen maalaus valmis. Smart-tila pois päältä: vain siveltimen/telan jälki maalattiin.');};
 const restore=(i:number)=>{const c=paintRef.current,frame=history[i];if(!c||!frame)return;const img=new Image();img.onload=()=>{const ctx=c.getContext('2d');ctx?.clearRect(0,0,c.width,c.height);ctx?.drawImage(img,0,0);setHistoryIndex(i);};img.src=frame;};
 const reset=()=>{const c=paintRef.current;if(!c)return;c.getContext('2d')?.clearRect(0,0,c.width,c.height);commit();};
 const download=(type:'png'|'jpg')=>{const img=imageRef.current,paint=paintRef.current;if(!img||!paint||!size.width)return;const out=document.createElement('canvas');out.width=size.width;out.height=size.height;const ctx=out.getContext('2d');if(!ctx)return;ctx.drawImage(img,0,0,size.width,size.height);ctx.drawImage(paint,0,0);ctx.fillStyle='rgba(255,255,255,.82)';ctx.fillRect(12,size.height-34,Math.min(330,size.width-24),22);ctx.fillStyle='#172033';ctx.font='12px sans-serif';ctx.fillText('VäriKamu · maalausmultivari.fi',20,size.height-19);const a=document.createElement('a');a.download=`varikamu-${Date.now()}.${type}`;a.href=type==='jpg'?out.toDataURL('image/jpeg',.93):out.toDataURL('image/png');a.click();};
 const ratio=size.width&&size.height?size.width/size.height:4/3,stageWidth=size.width?`min(100%, calc(58dvh * ${ratio}))`:'100%';
 const paintStyle=useMemo(()=>viewMode==='before'?{display:'none'}:viewMode==='compare'?{clipPath:`inset(0 ${100-compareAt}% 0 0)`}:undefined,[viewMode,compareAt]);

 return <section className="min-h-screen w-full overflow-x-hidden bg-navy-50 px-2 py-3 sm:px-3 sm:py-4"><div className="container-base w-full max-w-6xl overflow-x-hidden">
  <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wider text-orange-600">VäriKamu</p><h1 className="font-display text-xl font-extrabold text-navy-950 sm:text-2xl">Maalaa luonnollisesti — Smart auttaa automaattisesti</h1></div><button className="btn-outline" onClick={()=>setShowGuide(v=>!v)}><HelpCircle className="size-4"/>Ohje</button></div>
  {showGuide&&<div className="mb-4 rounded-2xl border border-orange-200 bg-orange-50 p-4"><div className="grid gap-2 text-sm sm:grid-cols-5"><strong>1. 📷 Lisää kuva</strong><strong>2. 🛡️ Suojaa reunat</strong><strong>3. 🎨 Valitse väri</strong><strong>4. 🖌️ Maalaa vihje</strong><strong>5. 👁️ Tarkista & lataa</strong></div><p className="mt-2 text-xs text-navy-700">Smart ON: lyhyt siveltimen/telan jälki toimii vihjeenä ja VäriKamu yrittää täydentää pinnan. Manual: vain oma jälkesi maalataan. Suojaus ei tule ladattuun kuvaan.</p></div>}
  <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_350px]"><div className="card min-w-0 overflow-hidden p-2 sm:p-4">
   {!imageUrl?<div className="grid min-h-[46vh] place-items-center rounded-2xl border-2 border-dashed border-navy-200 bg-white p-5 text-center"><div><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-4 text-xl font-bold">Ota kuva tai lataa kuva</h2><div className="mt-5 flex flex-wrap justify-center gap-3"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/>Ota kuva</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Lataa kuva</button></div></div></div>:<>
    <div className="w-full overflow-hidden rounded-2xl bg-navy-950 p-1" style={{maxHeight:'64dvh'}}><div className="flex min-h-[260px] items-center justify-center overflow-hidden"><div ref={stageRef} className="relative shrink-0 overflow-hidden rounded-xl bg-black select-none" style={{width:stageWidth,aspectRatio:`${size.width}/${size.height}`,maxWidth:'100%',transform:`scale(${zoom})`,transformOrigin:'center',touchAction:'none',userSelect:'none',cursor:'crosshair'}} onDragStart={e=>e.preventDefault()} onContextMenu={e=>e.preventDefault()} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onLostPointerCapture={pointerUp}><img ref={imageRef} src={imageUrl} onLoad={onImageLoad} draggable={false} className="pointer-events-none absolute inset-0 h-full w-full select-none object-fill"/><canvas ref={paintRef} className="pointer-events-none absolute inset-0 h-full w-full" style={paintStyle}/><canvas ref={protectRef} className={`pointer-events-none absolute inset-0 h-full w-full transition-opacity ${showProtection?'opacity-100':'opacity-0'}`}/>{viewMode==='compare'&&<><div className="pointer-events-none absolute inset-y-0 z-20 w-0.5 bg-white" style={{left:`${compareAt}%`}}/><span className="pointer-events-none absolute left-2 top-2 rounded-full bg-black/60 px-2 py-1 text-[10px] font-bold text-white">Jälkeen</span><span className="pointer-events-none absolute right-2 top-2 rounded-full bg-black/60 px-2 py-1 text-[10px] font-bold text-white">Ennen</span></>}</div></div></div>
    <div className="mt-2 flex flex-wrap items-center gap-2"><button className="btn-outline" onClick={()=>setZoom(z=>Math.max(1,z-.25))}><ZoomOut className="size-4"/>−</button><button className="btn-outline" onClick={()=>setZoom(1)}><Maximize2 className="size-4"/>Sovita</button><button className="btn-outline" onClick={()=>setZoom(z=>Math.min(2.5,z+.25))}><ZoomIn className="size-4"/>+</button><span className="text-xs">{Math.round(zoom*100)}%</span></div>
    <div className="mt-3 grid grid-cols-3 gap-2"><button className={viewMode==='before'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('before')}>Ennen</button><button className={viewMode==='after'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('after')}>Jälkeen</button><button className={viewMode==='compare'?'btn-primary':'btn-outline'} onClick={()=>setViewMode('compare')}>Vertaa</button></div>{viewMode==='compare'&&<input className="mt-3 w-full accent-orange-500" type="range" min="5" max="95" value={compareAt} onChange={e=>setCompareAt(Number(e.target.value))}/>}</>}
   <input ref={fileRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>loadFile(e.target.files?.[0])}/><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>loadFile(e.target.files?.[0])}/>
   {imageUrl&&<div className="mt-2 flex flex-wrap gap-2"><button className="btn-outline" onClick={()=>historyIndex>0&&restore(historyIndex-1)} disabled={historyIndex<=0}><Undo2 className="size-4"/>Kumoa</button><button className="btn-outline" onClick={()=>historyIndex<history.length-1&&restore(historyIndex+1)} disabled={historyIndex>=history.length-1}><Redo2 className="size-4"/>Tee uudelleen</button><button className="btn-outline" onClick={reset}><RotateCcw className="size-4"/>Tyhjennä maalit</button><button className="btn-outline" onClick={()=>setShowProtection(v=>!v)}>{showProtection?<EyeOff className="size-4"/>:<Eye className="size-4"/>}{showProtection?'Piilota suoja':'Näytä suoja'}</button><button className="btn-outline" onClick={clearProtection}><Shield className="size-4"/>Poista suojaukset</button></div>}
  </div><aside className="min-w-0 space-y-4">
   <div className="card p-4"><h2 className="font-bold">1. Maalaustapa</h2><div className="mt-3 grid grid-cols-2 gap-2"><button className={tool==='brush'?'btn-primary':'btn-outline'} onClick={()=>{setTool('brush');setViewMode('after');}}><Paintbrush className="size-4"/>Sivellin</button><button className={tool==='roller'?'btn-primary':'btn-outline'} onClick={()=>{setTool('roller');setViewMode('after');}}><PaintRoller className="size-4"/>Tela</button><button className={tool==='eraser'?'btn-primary':'btn-outline'} onClick={()=>{setTool('eraser');setViewMode('after');}}><Eraser className="size-4"/>Pyyhin</button><button className={tool==='cover'?'btn-primary':'btn-outline'} onClick={()=>{setTool('cover');setShowProtection(true);setViewMode('after');}}><Shield className="size-4"/>Suojaa</button></div><button className={`mt-3 flex w-full items-center justify-between rounded-xl border p-3 text-left ${smartAssist?'border-orange-400 bg-orange-50':'border-navy-200 bg-white'}`} onClick={()=>setSmartAssist(v=>!v)}><span><strong className="block"><Sparkles className="mr-1 inline size-4"/>Smart {smartAssist?'ON':'OFF'}</strong><span className="text-xs text-navy-600">{smartAssist?'Täyttää pintaa automaattisesti vihjeen jälkeen':'Manuaalinen: vain oma siveltimen jälki'}</span></span><span className="text-lg">{smartAssist?'✓':'○'}</span></button></div>
   {tool==='cover'&&<div className="card p-4"><h2 className="font-bold">2. Suojauksen leveys</h2><p className="mt-1 text-xs text-navy-600">Vedä reunaa pitkin. VäriKamu suoristaa lähes vaaka- ja pystysuorat vedot automaattisesti.</p><div className="mt-3 grid grid-cols-4 gap-2">{covers.map(c=><button key={c.label} className={`rounded-xl border p-2 text-xs font-bold ${coverSize===c.px?'border-orange-500 bg-orange-50':'border-navy-200'}`} onClick={()=>setCoverSize(c.px)}>{c.label}</button>)}</div></div>}
   <div className="card p-4"><h2 className="font-bold">3. Siveltimen tyyppi</h2><div className="mt-3 grid grid-cols-5 gap-2">{brushes.map(b=><button key={b.id} onClick={()=>{setBrushSize(b.px);setTool('brush');}} className={`rounded-xl border p-2 text-center ${brushSize===b.px&&tool==='brush'?'border-orange-500 bg-orange-50':'border-navy-100'}`}><span className="mx-auto block rounded-sm bg-navy-900" style={{width:`${Math.max(7,b.px*.3)}px`,height:'28px'}}/><strong className="mt-1 block text-[10px]">{b.label}</strong><span className="block text-[8px] text-navy-500">{b.detail}</span></button>)}</div></div>
   <div className="card p-4"><h2 className="font-bold">4. Väri</h2><div className="mt-3 flex flex-wrap gap-2">{palette.map(c=><button key={c} aria-label={c} onClick={()=>setColor(c)} className={`h-9 w-9 rounded-full border-2 ${color===c?'border-orange-500 ring-2 ring-orange-200':'border-white'}`} style={{backgroundColor:c}}/>)}<input type="color" value={color} onChange={e=>setColor(e.target.value)} className="h-9 w-12"/></div></div>
   <div className="card p-4"><label className="text-sm font-bold">Käden vakautus {stabilizer}%<input className="mt-2 w-full accent-orange-500" type="range" min="0" max="90" value={stabilizer} onChange={e=>setStabilizer(Number(e.target.value))}/></label><label className="mt-4 block text-sm font-bold">Maalikerrokset {passes}<input className="mt-2 w-full accent-orange-500" type="range" min="1" max="4" step="1" value={passes} onChange={e=>setPasses(Number(e.target.value))}/></label><p className="mt-1 text-xs text-navy-500">Useampi ohut kerros näyttää luonnollisemmalta kuin yksi peittävä kerros.</p><label className="mt-4 block text-sm font-bold">Peittävyys {Math.round(opacity*100)}%<input className="mt-2 w-full accent-orange-500" type="range" min="20" max="70" value={Math.round(opacity*100)} onChange={e=>setOpacity(Number(e.target.value)/100)}/></label>{smartAssist&&<><label className="mt-4 block text-sm font-bold">Smart-herkkyys {tolerance}<input className="mt-2 w-full accent-orange-500" type="range" min="35" max="90" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></label><label className="mt-4 block text-sm font-bold">Rajojen suojaus {edgeLock}%<input className="mt-2 w-full accent-orange-500" type="range" min="35" max="90" value={edgeLock} onChange={e=>setEdgeLock(Number(e.target.value))}/></label></>}</div>
   <div className="card p-4"><p className="text-sm leading-6 text-navy-700">{message}</p><div className="mt-3 grid grid-cols-2 gap-2"><button className="btn-outline" disabled={!imageUrl} onClick={()=>download('png')}><Download className="size-4"/>PNG</button><button className="btn-primary" disabled={!imageUrl} onClick={()=>download('jpg')}><Download className="size-4"/>JPG</button></div></div>
  </aside></div>
 </div></section>;
}
