import { useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Camera, Download, Eraser, Paintbrush, PaintRoller, RotateCcw, Upload } from 'lucide-react';

type Point={x:number;y:number};
type Tool='scraper'|'putty'|'sand'|'brush'|'roller'|'eraser';
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const palette=['#F2EFE6','#D8C9B5','#C9CBC8','#A7B19B','#9FB4C3','#B86F52','#496255','#45494B','#1D2022','#FF6B9D','#6C5CE7','#00B894'];
const rgb=(hex:string)=>{const n=parseInt(hex.slice(1),16);return{r:(n>>16)&255,g:(n>>8)&255,b:n&255};};

export function VarikamuRepairStudioV2Page(){
 const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),imgRef=useRef<HTMLImageElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),sourceRef=useRef<HTMLCanvasElement|null>(null),stageRef=useRef<HTMLDivElement>(null);
 const drawing=useRef(false),last=useRef<Point|null>(null);
 const [url,setUrl]=useState<string|null>(null),[size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('scraper'),[width,setWidth]=useState(46),[color,setColor]=useState('#F2EFE6'),[coats,setCoats]=useState(3),[view,setView]=useState<'before'|'after'>('after'),[message,setMessage]=useState('Aloita Kaavin/lastalla vaurioituneesta kohdasta. Sen jälkeen Kitti → Hionta → Maalaus ×3.');
 const [history,setHistory]=useState<string[]>([]),[hi,setHi]=useState(-1);

 const load=(f?:File)=>{if(!f||!f.type.startsWith('image/'))return;if(url?.startsWith('blob:'))URL.revokeObjectURL(url);setUrl(URL.createObjectURL(f));setView('after');};
 const onLoad=()=>{const img=imgRef.current,c=canvasRef.current;if(!img||!c)return;const s=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.round(img.naturalWidth*s),h=Math.round(img.naturalHeight*s);setSize({width:w,height:h});c.width=w;c.height=h;c.getContext('2d')?.clearRect(0,0,w,h);const src=document.createElement('canvas');src.width=w;src.height=h;src.getContext('2d')?.drawImage(img,0,0,w,h);sourceRef.current=src;const snap=c.toDataURL();setHistory([snap]);setHi(0);};
 const p=(e:ReactPointerEvent<HTMLDivElement>)=>{const r=stageRef.current?.getBoundingClientRect();if(!r||!size.width)return null;return{x:clamp((e.clientX-r.left)/r.width*size.width,0,size.width-1),y:clamp((e.clientY-r.top)/r.height*size.height,0,size.height-1)};};
 const commit=()=>{const c=canvasRef.current;if(!c)return;const n=[...history.slice(0,hi+1),c.toDataURL()].slice(-35);setHistory(n);setHi(n.length-1);};
 const restore=(i:number)=>{const c=canvasRef.current,s=history[i];if(!c||!s)return;const im=new Image();im.onload=()=>{const x=c.getContext('2d');x?.clearRect(0,0,c.width,c.height);x?.drawImage(im,0,0);setHi(i);};im.src=s;};
 const mask=(a:Point,b:Point,w:number)=>{const m=document.createElement('canvas');m.width=size.width;m.height=size.height;const x=m.getContext('2d')!;x.strokeStyle='#fff';x.lineWidth=w;x.lineCap=tool==='roller'?'square':'round';x.lineJoin='round';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();return m;};
 const compositeBase=()=>{const out=document.createElement('canvas'),src=sourceRef.current,fx=canvasRef.current;if(!src||!fx)return null;out.width=src.width;out.height=src.height;const x=out.getContext('2d')!;x.drawImage(src,0,0);x.drawImage(fx,0,0);return out;};
 const prepStroke=(a:Point,b:Point,mode:'scraper'|'putty'|'sand')=>{const target=canvasRef.current,base=compositeBase();if(!target||!base)return;const m=mask(a,b,width),tx=target.getContext('2d')!,temp=document.createElement('canvas');temp.width=target.width;temp.height=target.height;const x=temp.getContext('2d')!;
   if(mode==='scraper'){x.filter='blur(2.2px) saturate(.72) contrast(.82)';x.drawImage(base,0,0);x.filter='none';x.globalCompositeOperation='destination-in';x.drawImage(m,0,0);tx.drawImage(temp,0,0);setMessage('Kaavin: hilseilevän/rosoisen kohdan kontrastia ja pintarakennetta tasoitetaan. Jatka Kitti/paikkaus-työkalulla.');}
   if(mode==='putty'){const bx=base.getContext('2d')!,d=bx.getImageData(0,0,base.width,base.height),md=m.getContext('2d')!.getImageData(0,0,m.width,m.height).data,o=x.createImageData(base.width,base.height);for(let i=0;i<o.data.length;i+=4){if(!md[i+3])continue;const lum=(d.data[i]+d.data[i+1]+d.data[i+2])/3,pl=clamp(lum*.32+196,190,238);o.data[i]=pl;o.data[i+1]=clamp(pl+2,0,255);o.data[i+2]=clamp(pl+1,0,255);o.data[i+3]=218;}x.putImageData(o,0,0);tx.drawImage(temp,0,0);setMessage('Kitti: valittu kohta peitetään tasaisella paikkausmassalla. Jatka Hionta-työkalulla reunojen tasoittamiseksi.');}
   if(mode==='sand'){x.filter='blur(4px) contrast(.92)';x.drawImage(base,0,0);x.filter='none';x.globalCompositeOperation='destination-in';x.drawImage(m,0,0);tx.save();tx.globalAlpha=.92;tx.drawImage(temp,0,0);tx.restore();setMessage('Hionta: paikkaus ja rosoisuus tasoitetaan pehmeästi. Pinta on valmis kolmen kerroksen maalaukseen.');}
 };
 const paintStroke=(a:Point,b:Point)=>{const target=canvasRef.current,src=sourceRef.current;if(!target||!src)return;const m=mask(a,b,tool==='roller'?width*1.8:width),md=m.getContext('2d')!.getImageData(0,0,m.width,m.height).data,sd=src.getContext('2d')!.getImageData(0,0,src.width,src.height).data,col=rgb(color),temp=document.createElement('canvas');temp.width=target.width;temp.height=target.height;const x=temp.getContext('2d')!,o=x.createImageData(temp.width,temp.height);const alpha=[0,.28,.46,.62][clamp(coats,1,3)];for(let i=0;i<o.data.length;i+=4){if(!md[i+3])continue;const lum=(sd[i]*.299+sd[i+1]*.587+sd[i+2]*.114)/255,shade=.58+lum*.52;o.data[i]=clamp(Math.round(col.r*shade),0,255);o.data[i+1]=clamp(Math.round(col.g*shade),0,255);o.data[i+2]=clamp(Math.round(col.b*shade),0,255);o.data[i+3]=Math.round(alpha*255);}x.putImageData(o,0,0);target.getContext('2d')!.drawImage(temp,0,0);setMessage(`Maalaus: ${coats}/3 kerrosta. Alkuperäisen kuvan valo ja varjot säilyvät värin alla.`);};
 const draw=(a:Point,b:Point)=>{if(tool==='eraser'){const x=canvasRef.current?.getContext('2d');if(!x)return;x.save();x.globalCompositeOperation='destination-out';x.lineWidth=width;x.lineCap='round';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();x.restore();return;}if(tool==='scraper'||tool==='putty'||tool==='sand')prepStroke(a,b,tool);else paintStroke(a,b);};
 const down=(e:ReactPointerEvent<HTMLDivElement>)=>{if(view!=='after')return;const q=p(e);if(!q)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;last.current=q;};
 const move=(e:ReactPointerEvent<HTMLDivElement>)=>{if(!drawing.current||!last.current)return;const q=p(e);if(!q)return;e.preventDefault();draw(last.current,q);last.current=q;};
 const up=()=>{if(!drawing.current)return;drawing.current=false;last.current=null;commit();};
 const reset=()=>{const c=canvasRef.current;if(!c)return;c.getContext('2d')?.clearRect(0,0,c.width,c.height);commit();setMessage('Kaikki esikatselumuutokset poistettiin.');};
 const download=()=>{const src=sourceRef.current,fx=canvasRef.current;if(!src||!fx)return;const o=document.createElement('canvas');o.width=src.width;o.height=src.height;const x=o.getContext('2d')!;x.drawImage(src,0,0);x.drawImage(fx,0,0);const a=document.createElement('a');a.download=`varikamu-${Date.now()}.jpg`;a.href=o.toDataURL('image/jpeg',.94);a.click();};
 const tools:[Tool,string][]=[['scraper','🔪 Kaavin / lasta'],['putty','🧱 Kitti / paikkaus'],['sand','🟤 Hionta'],['brush','🖌️ Sivellin'],['roller','🧰 Tela'],['eraser','⌫ Pyyhin']];
 return <section className="min-h-screen bg-navy-50 px-2 py-4"><div className="container-base max-w-6xl"><div className="mb-3"><p className="text-xs font-bold uppercase text-orange-600">VäriKamu PRO</p><h1 className="text-2xl font-extrabold text-navy-950">Korjaa pinta oikeassa järjestyksessä ja maalaa 3 kerrosta</h1><p className="mt-1 text-sm text-navy-600">1. Kaavi → 2. Kittaa → 3. Hio → 4. Maalaa. Jokainen valmistelutyökalu muuttaa nyt kuvaa omalla toiminnollaan.</p></div><div className="grid gap-4 lg:grid-cols-[1fr_330px]"><div className="card p-3">{!url?<div className="grid min-h-[55vh] place-items-center rounded-2xl border-2 border-dashed p-6 text-center"><div><Camera className="mx-auto size-12 text-orange-500"/><h2 className="mt-3 text-xl font-bold">Lisää korjattavan pinnan kuva</h2><div className="mt-4 flex gap-2"><button className="btn-primary" onClick={()=>cameraRef.current?.click()}><Camera className="size-4"/>Kamera</button><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Lataa</button></div></div></div>:<><div ref={stageRef} className="relative mx-auto overflow-hidden rounded-2xl bg-navy-950" style={{aspectRatio:`${size.width}/${size.height}`,maxHeight:'62vh',touchAction:'none'}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><img ref={imgRef} src={url} onLoad={onLoad} draggable={false} className="absolute inset-0 h-full w-full select-none"/><canvas ref={canvasRef} className="absolute inset-0 h-full w-full" style={{display:view==='before'?'none':'block'}}/></div><div className="mt-3 grid grid-cols-2 gap-2"><button className={view==='before'?'btn-primary':'btn-outline'} onClick={()=>setView('before')}>Ennen</button><button className={view==='after'?'btn-primary':'btn-outline'} onClick={()=>setView('after')}>Jälkeen</button></div><div className="mt-3 flex flex-wrap gap-2"><button className="btn-outline" disabled={hi<=0} onClick={()=>restore(hi-1)}>↶ Kumoa</button><button className="btn-outline" disabled={hi>=history.length-1} onClick={()=>restore(hi+1)}>↷ Tee uudelleen</button><button className="btn-outline" onClick={reset}><RotateCcw className="size-4"/>Tyhjennä</button><button className="btn-primary" onClick={download}><Download className="size-4"/>Lataa JPG</button></div></>}
 <input ref={fileRef} className="hidden" type="file" accept="image/*" onChange={e=>load(e.target.files?.[0])}/><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>load(e.target.files?.[0])}/></div><aside className="space-y-4"><div className="card p-4"><h2 className="font-bold">1. Työvaihe</h2><div className="mt-3 grid grid-cols-2 gap-2">{tools.map(([id,label])=><button key={id} className={tool===id?'btn-primary':'btn-outline'} onClick={()=>{setTool(id);setMessage(id==='scraper'?'Kaavi vaurioitunut/hilseilevä kohta.':id==='putty'?'Levitä kitti korjattavaan kohtaan.':id==='sand'?'Hio kitattu kohta tasaiseksi.':'Työkalu valittu.');}}>{id==='brush'?<Paintbrush className="size-4"/>:id==='roller'?<PaintRoller className="size-4"/>:id==='eraser'?<Eraser className="size-4"/>:null}{label}</button>)}</div></div><div className="card p-4"><label className="font-bold">Työkalun leveys {width}px</label><input className="mt-2 w-full accent-orange-500" type="range" min="12" max="120" value={width} onChange={e=>setWidth(Number(e.target.value))}/>{(tool==='brush'||tool==='roller')&&<><h3 className="mt-4 font-bold">2. Väri</h3><div className="mt-2 flex flex-wrap gap-2">{palette.map(c=><button key={c} aria-label={c} className="size-9 rounded-full border-2" style={{background:c,borderColor:color===c?'#f97316':'white'}} onClick={()=>setColor(c)}/>)}</div><h3 className="mt-4 font-bold">3. Maalikerrokset</h3><div className="mt-2 grid grid-cols-3 gap-2">{[1,2,3].map(n=><button key={n} className={coats===n?'btn-primary':'btn-outline'} onClick={()=>setCoats(n)}>{n}×</button>)}</div><p className="mt-2 text-xs text-navy-600">3× = kolme luonnollista peittokerrosta. Valo ja varjot säilyvät.</p></>}</div><div className="card p-4 text-sm"><strong>Tila</strong><p className="mt-2 text-navy-700">{message}</p></div></aside></div></div></section>;
}
